---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: NetApp Backup and Recovery 의 이 릴리스에는 다음과 같은 알려진 제한 사항이 있습니다. 
---
= KVM 워크로드에 대한 NetApp Backup and Recovery 의 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 버전에서 작동하지 않거나 제대로 작동하지 않는 플랫폼, 장치 또는 기능은 다음과 같습니다.  이러한 제한 사항을 주의 깊게 읽으십시오.

NetApp Backup and Recovery 의 KVM 워크로드 비공개 미리 보기 버전에서는 다음 작업 및 구성이 지원되지 않습니다.



== 지원되지 않는 작업

다음 작업은 비공개 미리보기 릴리스에서 지원되지 않습니다.

* VM 복제, 마운트 또는 마운트 해제
* VM을 대체 위치로 복원
* SAN에 저장된 VM 보호
* 애플리케이션 보호
* 보호 그룹 편집
* 여러 KVM 호스트의 VM을 사용하여 보호 그룹 만들기
* 사용자 정의 백업 생성( NetApp Console 에서 시작된 백업만 지원됨)




== 지원되지 않는 구성

다음 구성은 지원되지 않습니다.

* 역할 기반 접근 제어(RBAC)
* KVM 호스트에 직접 연결된 디스크
* 여러 NFS 마운트 지점 또는 공유에 걸쳐 있는 디스크
* RAW 디스크 포맷
* NetFS 이외의 스토리지 풀 유형(NetFS만 지원됨)




== 지원되지 않는 레거시 NetApp Console 계정

기존 NetApp Console 계정은 KVM 워크로드를 보호하는 데 필요한 기능을 지원하지 않습니다.  콘솔 웹 UI에서 레거시 계정을 사용하고 있는지 확인하세요.  기존 콘솔 계정이 있는 경우 KVM 작업 부하를 보호하기 전에 새 계정을 만드세요.

.단계
. NetApp Console 메뉴에서 *관리 > ID 및 액세스*를 선택합니다.
. *조직*에서 조직 ID 옆에 *계정 ID*가 표시되는지 확인하세요.
+
*계정 ID*가 표시되면 기존 계정을 사용하고 있는 것입니다.

. 기존 계정을 사용하는 경우 다음을 수행하세요.
+
.. 콘솔에서 로그아웃한 다음 탐색하세요. https://console.netapp.com/["콘솔 로그인 페이지"^] .
.. *가입*을 선택하여 새 계정을 만드세요.



