---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: NetApp Backup and Recovery 의 이 릴리스에는 다음과 같은 알려진 제한 사항이 있습니다. 
---
= KVM 워크로드에 대한 NetApp Backup and Recovery 의 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 버전에서 작동하지 않거나 제대로 작동하지 않는 플랫폼, 장치 또는 기능은 다음과 같습니다.  이러한 제한 사항을 주의 깊게 읽으십시오.

NetApp Backup and Recovery 의 KVM 워크로드 비공개 미리 보기 버전에서는 다음 작업 및 구성이 지원되지 않습니다.



== 지원되지 않는 작업

다음 작업은 비공개 미리보기 릴리스에서 지원되지 않습니다.

* VM 복제, 마운트 또는 마운트 해제
* VM을 대체 위치로 복원
* SAN에 저장된 VM 보호
* 애플리케이션 보호
* 보호 그룹 편집
* 여러 KVM 호스트의 VM을 사용하여 보호 그룹 만들기
* 사용자 정의 백업 생성( NetApp Console 에서 시작된 백업만 지원됨)




== 지원되지 않는 구성

다음 구성은 지원되지 않습니다.

* 역할 기반 접근 제어(RBAC)
* KVM 호스트에 직접 연결된 디스크
* 여러 NFS 마운트 지점 또는 공유에 걸쳐 있는 디스크
* RAW 디스크 포맷
* NetFS 이외의 스토리지 풀 유형(NetFS만 지원됨)




== 문제 해결 참고 사항

NetApp Backup and Recovery 에서 KVM 워크로드의 비공개 미리 보기를 사용할 때 다음 사항에 유의하십시오.

* KVM 워크로드 복원이 성공적으로 완료되도록 하려면 KVM 백업에 사용하는 보호 정책에서 *VM 일관성 스냅샷 사용* 설정이 활성화되어 있는지 확인하십시오.
* Apache CloudStack에서 관리하는 KVM 호스트가 포함된 스토리지 풀을 백업하려면 모든 관리 호스트를 NetApp Backup and Recovery 에 추가해야 합니다. 임시 해결책으로 CloudStack에서 관리하는 모든 KVM 호스트를 NetApp Backup and Recovery 에 추가하십시오.
* 보호 그룹에 속한 중지된 가상 머신은 백업할 수 없습니다. 임시 해결책으로, 백업을 시작하기 전에 중지된 VM을 보호 그룹에서 제거하십시오.

