---
sidebar: sidebar 
permalink: br-reference-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않는 기능이나 이 릴리스와 올바르게 상호 운용되지 않는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요. 
---
= ONTAP 볼륨에 대한 NetApp Backup and Recovery의 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 NetApp Backup and Recovery의 이번 릴리스에서 지원되지 않거나 올바르게 상호 운용되지 않는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요.

* NetApp Backup and Recovery는 Cloud Volumes ONTAP AWS 중국 지역(베이징 및 닝샤 포함)의 개체 저장소에 백업할 수 있습니다. 하지만 먼저 ID 및 액세스 정책을 수동으로 수정해야 할 수도 있습니다.
+
AWS에서 콘솔 에이전트를 만드는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-bluexp.html["AWS에 콘솔 에이전트 설치"^] .

+
자세한 내용은 블로그 게시물을 참조하세요. https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-May-23-Updates/ba-p/444052["NetApp 백업 및 복구 기능 블로그 2023년 5월"^] .

* NetApp Backup and Recovery는 Microsoft Azure 중국 지역을 지원하지 않습니다.
+
Azure에서 콘솔 에이전트를 만드는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-azure-bluexp.html["Azure에 콘솔 에이전트 설치"^] .

* NetApp Backup and Recovery는 FlexCache 볼륨의 백업을 지원하지 않습니다.




== ONTAP 볼륨에 대한 복제 제한

* 한 번에 하나의 FlexGroup 볼륨만 복제하도록 선택할 수 있습니다.  각 FlexGroup 볼륨에 대해 별도로 백업을 활성화해야 합니다.
+
FlexVol 볼륨에는 제한이 없습니다. 시스템의 모든 FlexVol 볼륨을 선택하고 동일한 백업 정책을 할당할 수 있습니다.

* 다음 기능이 지원됩니다. https://docs.netapp.com/us-en/data-services-replication/index.html["NetApp 복제"] 하지만 NetApp Backup and Recovery의 복제 기능을 사용하는 경우는 그렇지 않습니다.
+
** 볼륨 A에서 볼륨 B로, 볼륨 B에서 볼륨 C로 복제가 발생하는 계단식 구성은 지원되지 않습니다. 볼륨 A에서 볼륨 B로의 복제는 지원됩니다.
** FSx for ONTAP 시스템에서 데이터를 복제하는 기능은 지원되지 않습니다.
** 볼륨의 일회성 복제를 생성하는 기능은 지원되지 않습니다.


* 온프레미스 ONTAP 시스템에서 복제를 생성할 때 대상 Cloud Volumes ONTAP 시스템의 ONTAP 버전이 9.8, 9.9 또는 9.11인 경우 미러 볼트 정책만 허용됩니다.




== ONTAP 볼륨에 대한 객체 백업 제한 사항

* 데이터를 백업할 때 NetApp Backup and Recovery는 NetApp Volume Encryption(NVE)을 유지하지 않습니다.  즉, NVE 볼륨의 암호화된 데이터는 목적지로 전송되는 동안 암호 해독되고 암호화는 유지되지 않습니다.
+
이러한 암호화 유형에 대한 설명은 다음을 참조하세요.https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["NetApp 볼륨 암호화 구성 개요"^] .



* SnapMirror 정책의 일정을 사용하여 SnapMirror 대상 볼륨에서 장기 보존 스냅샷이 활성화된 경우 스냅샷은 대상 볼륨에 직접 생성됩니다.  이 경우 NetApp Backup and Recovery를 사용하여 해당 볼륨을 백업하면 안 됩니다. 해당 스냅샷은 개체 스토리지로 이동되지 않습니다.
* 데이터를 백업할 때 NetApp Backup and Recovery는 NetApp Volume Encryption(NVE)을 유지하지 않습니다.  즉, NVE 볼륨의 암호화된 데이터는 목적지로 전송되는 동안 암호 해독되고 암호화는 유지되지 않습니다.
+
이러한 암호화 유형에 대한 설명은 다음을 참조하세요.https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["NetApp 볼륨 암호화 구성 개요"^] .



* SnapMirror 정책의 일정을 사용하여 SnapMirror 대상 볼륨에서 장기 보존 스냅샷이 활성화된 경우 스냅샷은 대상 볼륨에 직접 생성됩니다.  이 경우 NetApp Backup and Recovery를 사용하여 해당 볼륨을 백업하면 안 됩니다. 해당 스냅샷은 개체 스토리지로 이동되지 않습니다.
* 볼륨이 정책에 할당되지 않은 상태에서 백업 정책을 생성하거나 편집하는 경우 보관되는 백업 수는 최대 1018개입니다.  정책에 볼륨을 할당한 후 정책을 편집하여 최대 4000개의 백업을 만들 수 있습니다.
* 데이터 보호(DP) 볼륨을 백업할 때:
+
** SnapMirror 레이블과의 관계 `app_consistent` 그리고 `all_source_snapshot` 클라우드에 백업되지 않습니다.
** SnapMirror 대상 볼륨에 스냅샷의 로컬 복사본을 생성하는 경우(사용된 SnapMirror 레이블과 관계 없이) 이러한 스냅샷은 백업으로 클라우드로 이동되지 않습니다.  이때 NetApp Backup and Recovery에서 백업할 수 있도록 소스 DP 볼륨에 대한 원하는 레이블이 포함된 스냅샷 정책을 만들어야 합니다.


* FlexGroup 볼륨 백업은 보관 저장소로 이동할 수 없습니다.
* 클러스터가 ONTAP 9.13.1 이상을 실행하는 경우 FlexGroup 볼륨 백업은 DataLock 및 랜섬웨어 보호 기능을 사용할 수 있습니다.
* SVM-DR 볼륨 백업은 다음과 같은 제한 사항과 함께 지원됩니다.
+
** 백업은 ONTAP 보조에서만 지원됩니다.
** 볼륨에 적용되는 스냅샷 정책은 NetApp Backup and Recovery에서 인식하는 일일, 주간, 월간 등의 정책 중 하나여야 합니다. 기본 "sm_created" 정책(*모든 스냅샷 미러링*에 사용됨)은 인식되지 않으며 DP 볼륨은 백업 가능한 볼륨 목록에 표시되지 않습니다.
** 백업이 소스나 대상에서 수행되는 경우 SVM-DR과 볼륨 백업 및 복구는 완전히 독립적으로 작동합니다.  유일한 제한 사항은 SVM-DR이 SnapMirror 클라우드 관계를 복제하지 않는다는 것입니다.  DR 시나리오에서 SVM이 보조 위치에서 온라인 상태가 되면 SnapMirror 클라우드 관계를 수동으로 업데이트해야 합니다.




* MetroCluster 지원:
+
** ONTAP 9.12.1 GA 이상을 사용하는 경우 기본 시스템에 연결하면 백업이 지원됩니다.  전체 백업 구성이 보조 시스템으로 전송되므로 전환 후에도 클라우드로의 백업이 자동으로 계속됩니다.  보조 시스템에는 백업을 설정할 필요가 없습니다(사실, 설정하는 것이 제한되어 있습니다).
** ONTAP 9.12.0 및 이전 버전을 사용하는 경우 백업은 ONTAP 보조 시스템에서만 지원됩니다.
** 현재 FlexGroup 볼륨 백업은 지원되지 않습니다.


* 데이터 보호 볼륨에서는 *지금 백업* 버튼을 사용한 임시 볼륨 백업이 지원되지 않습니다.
* SM-BC 구성은 지원되지 않습니다.
* ONTAP 단일 볼륨에서 여러 개체 저장소로의 SnapMirror 관계 팬아웃을 지원하지 않습니다. 따라서 이 구성은 NetApp Backup and Recovery에서 지원되지 않습니다.
* 현재 Amazon S3, Azure 및 StorageGRID 에서는 객체 저장소의 WORM/규정 준수 모드가 지원됩니다.  이는 DataLock 기능으로 알려져 있으며, 클라우드 공급자 인터페이스가 아닌 NetApp 백업 및 복구 설정을 사용하여 관리해야 합니다.




== ONTAP 볼륨에 대한 복원 제한

이러한 제한 사항은 파일과 폴더를 복원하는 검색 및 복원 방법과 찾아보기 및 복원 방법 모두에 적용됩니다(특별히 언급되지 않는 한).

* 찾아보기 및 복원 기능은 한 번에 최대 100개의 개별 파일을 복원할 수 있습니다.
* 검색 및 복원은 한 번에 1개의 파일을 복원할 수 있습니다.
* ONTAP 9.13.0 이상을 사용하는 경우, 찾아보기 및 복원과 검색 및 복원을 통해 폴더와 그 안의 모든 파일 및 하위 폴더를 복원할 수 있습니다.
+
9.11.1보다 크고 9.13.0 이전의 ONTAP 버전을 사용하는 경우, 복원 작업은 선택한 폴더와 해당 폴더의 파일만 복원할 수 있으며, 하위 폴더나 하위 폴더의 파일은 복원되지 않습니다.

+
9.11.1 이전 버전의 ONTAP 사용하는 경우 폴더 복원이 지원되지 않습니다.

* 디렉토리/폴더 복원은 클러스터가 ONTAP 9.13.1 이상을 실행하는 경우에만 보관 저장소에 있는 데이터에 대해 지원됩니다.
* DataLock을 사용하여 보호되는 데이터에 대해서만 디렉터리/폴더 복원이 지원되며, 클러스터가 ONTAP 9.13.1 이상을 실행하는 경우에만 가능합니다.
* 현재 복제 및/또는 로컬 스냅샷에서는 디렉토리/폴더 복원이 지원되지 않습니다.
* FlexGroup 볼륨에서 FlexVol 볼륨으로, 또는 FlexVol 볼륨에서 FlexGroup 볼륨으로 복원하는 것은 지원되지 않습니다.
* 복원되는 파일은 대상 볼륨의 언어와 동일한 언어를 사용해야 합니다.  언어가 같지 않으면 오류 메시지가 표시됩니다.
* Azure 보관 저장소에서 StorageGRID 시스템으로 데이터를 복원하는 경우 _높음_ 복원 우선 순위는 지원되지 않습니다.
* DP 볼륨을 백업한 후 해당 볼륨에 대한 SnapMirror 관계를 끊기로 결정한 경우 SnapMirror 관계도 삭제하거나 SnapMirror 방향을 반전하지 않는 한 해당 볼륨에 파일을 복원할 수 없습니다.
* 빠른 복원 제한 사항:
+
** 대상 위치는 ONTAP 9.13.0 이상을 사용하는 Cloud Volumes ONTAP 시스템이어야 합니다.
** 보관된 저장소에 있는 백업에서는 지원되지 않습니다.
** FlexGroup 볼륨은 클라우드 백업이 생성된 소스 시스템에서 ONTAP 9.12.1 이상을 실행하는 경우에만 지원됩니다.
** SnapLock 볼륨은 클라우드 백업이 생성된 소스 시스템에서 ONTAP 9.11.0 이상을 실행하는 경우에만 지원됩니다.



