---
sidebar: sidebar 
permalink: br-rbac-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: 보안 강화를 위해 NetApp Backup and Recovery에서 특정 역할에 대한 액세스 권한을 구성하십시오. 
---
= NetApp Backup and Recovery에서 역할 기반 액세스 제어 설정
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Console에서 역할 기반 액세스 제어(RBAC)를 구성하여 NetApp Backup and Recovery 리소스에 액세스할 수 있는 사용자를 제어하십시오. RBAC를 지원하는 워크로드에는 관리자 또는 뷰어 역할을 할당할 수 있습니다. RBAC를 아직 지원하지 않는 워크로드는 프로젝트 수준 또는 플릿 수준 연결이 가능해질 때까지 Backup and Recovery 역할을 가진 모든 사용자가 액세스할 수 있습니다.


NOTE: NetApp Console은 폴더 내의 리소스를 구성하기 위해 프로젝트를 사용하며, NetApp Console 로컬 배포에서는 프로젝트를 플릿이라고 부릅니다.

조직 내 리소스에 대한 액세스를 제어하려면 NetApp Console의 *관리 > ID 및 액세스* 페이지에서 다음 단계를 완료하십시오.


NOTE: 이 단계는 NetApp Console에서 조직 관리자 역할이 할당된 경우를 가정합니다.

.단계
. ID 및 액세스 프로젝트 구조를 생성합니다.
+
조직 관리자로서 워크로드가 저장될 폴더 및 프로젝트 구조를 설정하십시오.

. 사용자 역할을 할당합니다.
+
.. 기본 옵션:
+
워크로드용으로 지정된 각 프로젝트에 사용자를 추가하고 적절한 역할을 부여합니다. 예를 들면 다음과 같습니다.

+
*** *Organization admin* 및 *Backup and Recovery super admin*: 이러한 역할을 가진 사용자는 조직 전체의 모든 리소스를 볼 수 있으며, Backup and Recovery 워크로드를 검색하고 프로젝트(예: US East 또는 US West)에 할당할 수 있습니다.
*** *폴더 또는 프로젝트 관리자* 및 *Backup and Recovery 슈퍼 관리자*: 이러한 역할을 가진 사용자는 할당된 폴더 또는 프로젝트의 리소스만 볼 수 있지만, Backup and Recovery 워크로드를 검색하고 해당 프로젝트에 할당할 수 있습니다.


.. 대체 옵션:
+
사용자에게 전체 NetApp Backup and Recovery 관리자 액세스 권한을 부여하는 대신 자신에게 NetApp Backup and Recovery 최고 관리자 역할을 할당하고 워크로드를 직접 검색할 수 있습니다.



. Backup and Recovery에서 워크로드를 검색합니다.
+
조직 관리자, 폴더 관리자 또는 프로젝트 관리자는 사용 가능한 워크로드를 검색하고 미국 동부 또는 미국 서부 등 적절한 프로젝트를 선택합니다. 각 워크로드는 선택한 프로젝트와 자동으로 연결됩니다.

. 프로젝트에 사용자를 추가합니다.
+
조직 관리자, 폴더 관리자 또는 프로젝트 관리자는 워크로드가 포함된 프로젝트에 NetApp Console 사용자를 추가합니다. 사용자의 액세스 요구 사항에 따라 조직 뷰어 역할과 Backup and Recovery 역할을 할당합니다. 적절한 Backup and Recovery 역할을 가진 사용자는 이러한 프로젝트의 새 워크로드에 자동으로 액세스할 수 있습니다.





[[related-information]]
== 관련 정보

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["NetApp Console ID 및 액세스 관리에 대해 알아보십시오"^].
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Console 의 NetApp Backup and Recovery 역할"^].

