---
sidebar: sidebar 
permalink: br-start-discover-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle 
summary: NetApp Backup and Recovery 워크로드를 보호하기 위해 먼저 워크로드를 검색해야 합니다. 
---
= NetApp Backup and Recovery에서 Oracle Database 워크로드를 검색하세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Oracle 데이터베이스를 검색하면 NetApp Backup and Recovery에서 백업 및 스냅샷을 생성하고 복원하여 데이터베이스를 보호할 수 있습니다.

*필수 콘솔 역할* 백업 및 복구 슈퍼 관리자.  에 대해 알아보세요link:reference-roles.html["백업 및 복구 역할과 권한"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp Console 액세스 역할에 대해 알아보세요."^] .



== Oracle 데이터베이스 호스트를 추가하고 리소스를 검색합니다

Oracle 호스트 정보를 추가하고 NetApp Backup and Recovery 워크로드를 검색하도록 합니다. 각 콘솔 에이전트 내에서 워크로드를 검색할 시스템을 선택합니다.

.단계
. NetApp Console 메뉴에서 *보호 > 백업 및 복구*를 선택합니다.
. *워크로드*에서 *Oracle* 타일을 선택하십시오.
. *리소스 검색*을 선택하세요.
. *워크로드 유형* 필드에서 *Oracle*을 선택하십시오.
. 이 Oracle Database 호스트에 대한 자격 증명을 아직 저장하지 않은 경우 *자격 증명 추가*를 선택하십시오.
+
.. 이 호스트와 함께 사용할 콘솔 에이전트를 선택하세요.
.. 이 자격증의 이름을 입력하세요.
.. 계정의 사용자 이름과 비밀번호를 입력하세요.
.. *완료*를 선택하세요.


. *호스트 등록*: 새 Oracle 데이터베이스 호스트를 추가합니다. *호스트 FQDN 또는 IP 주소* 필드에 호스트의 FQDN 또는 IP 주소를 입력합니다. 클러스터형 데이터베이스의 경우 클러스터 내 모든 노드의 FQDN 또는 IP를 입력할 수 있습니다. 그런 다음 자격 증명, NetApp Console 에이전트 및 포트 번호를 제공합니다.
. (선택 사항) 루트 사용자가 아닌 사용자의 자격 증명을 선택하는 경우 다음을 수행하십시오.
+
.. 선택한 루트가 아닌 사용자를 Oracle 데이터베이스 호스트의 sudoers 파일에 추가하는 방법에 대한 지침을 보려면 *sudoers 구성*을 선택하십시오.
.. 대화 상자의 지침을 따르고 완료되면 확인란을 활성화한 다음 *완료*를 선택하십시오.


. *고급 설정*: 다음을 수행하십시오:
+
.. NetApp 플러그인에 사용할 포트와 설치 경로를 입력하십시오. 이 플러그인을 사용하면 Oracle 데이터베이스 호스트와 NetApp Backup and Recovery 간의 통신이 가능해집니다.
.. NetApp Backup and Recovery에서 각 호스트에 플러그인을 자동으로 설치하도록 허용할지, 아니면 모든 호스트에 대한 자동 플러그인 설치를 건너뛸지 선택하십시오. 수동 설치 지침을 보려면 *방법 보기*를 선택하십시오.
+
[NOTE]
====
Backup and Recovery는 SSH를 통해 각 호스트에 연결하여 플러그인을 자동으로 설치합니다. 다음 중 하나에 해당하는 경우 *수동 설치 사용*을 활성화하십시오.

*** 하나 이상의 호스트에서 SSH 서비스가 실행되고 있지 않습니다.
*** 모든 호스트에 NetApp 플러그인이 이미 설치되어 있습니다(클러스터 멤버 중 일부에만 설치되어 있는 경우에도 마찬가지입니다).
*** 각 호스트에 플러그인을 수동으로 설치하는 것을 선호합니다.


====
.. 데이터베이스 호스트가 클러스터링된 경우 *클러스터의 모든 호스트 추가* 옵션을 활성화하여 클러스터의 모든 호스트를 검색합니다.
.. 플러그인을 자동으로 설치하기 전에 각 호스트에서 사전 설치 검사를 실행할지 여부를 선택하십시오. 검사에 실패하면 자동 플러그인 설치가 중지됩니다. 검사를 건너뛰고 설치하려면 *선택적 사전 설치 검사 건너뛰기*를 활성화하십시오(수동 설치를 선택하면 자동으로 활성화됩니다).


. *발견*을 선택하세요.
+

TIP: 리소스를 추가하는 데 몇 분 정도 소요될 수 있습니다. 진행 상황을 확인하려면 인벤토리 페이지 하단의 상태 대화 상자에서 *진행 상황 추적*을 선택하거나 왼쪽 메뉴에서 *모니터링*을 선택하세요.



.결과
Oracle 데이터베이스 워크로드는 인벤토리 페이지의 워크로드 목록에 표시됩니다.



== NetApp Backup and Recovery 보드로 계속

. NetApp Console 메뉴에서 *보호* > *백업 및 복구*를 선택합니다.
. 워크로드 타일(예: Microsoft SQL Server)을 선택합니다.
. 백업 및 복구 메뉴에서 *대시보드*를 선택합니다.
. 데이터 보호 상태를 검토하세요.  위험에 처한 작업이나 보호된 작업의 수는 새로 발견, 보호 및 백업된 작업 부하에 따라 증가합니다.

