---
sidebar: sidebar 
permalink: br-start-enable.html 
keywords: backup, Backup and Recovery, enable backup, Console, service, local deployment 
summary: NetApp Console 또는 NetApp Console 로컬 배포에서 시스템의 백업 및 복구를 활성화합니다. 
---
= NetApp Backup and Recovery를 활성화하여 볼륨을 보호합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Volumes 워크로드를 보호하려면 NetApp Console 또는 NetApp Console 로컬 배포에서 스토리지 시스템에 대해 NetApp Backup and Recovery를 활성화해야 합니다. 시스템을 추가할 때 또는 나중에 Backup and Recovery를 활성화할 수 있습니다.



[[enable-backup-and-recovery-in-netapp-console]]
== NetApp Console에서 백업 및 복구 활성화

NetApp Console에서 백업 및 복구 서비스를 활성화하십시오.

.단계
. * Volumes * 메뉴를 선택합니다.
. 볼륨 보호 개요 페이지에서 *백업 설정*을 선택합니다.
. 백업을 활성화할 시스템을 확인하고 *백업 활성화* 버튼을 선택하십시오.
. *다음*을 선택하세요.
. 보호할 소스 볼륨을 선택하고 *다음*을 선택하십시오.
. 백업 전략 정의 페이지에서 백업 아키텍처를 선택한 다음 로컬 스냅샷, 복제 볼륨 및 백업 파일에 대한 정책 및 기타 세부 정보를 정의합니다. 이 시스템에서 처음 활성화한 볼륨의 백업 옵션에 대한 세부 정보를 참조하십시오. 그런 다음 *다음*을 선택합니다.
. 선택적으로 백업 및 복구 기능이 일치하지 않는 백업, 스냅샷 및 복제 레이블을 자동으로 수정하도록 설정할 수 있습니다.
. 이 볼륨의 백업 설정을 검토한 다음 *백업 활성화*를 선택합니다.
. 보호한 볼륨은 볼륨 개요 페이지에 표시됩니다.




[[enable-backup-and-recovery-in-netapp-console-local-deployment]]
== NetApp Console 로컬 배포에서 백업 및 복구 활성화

NetApp Console 로컬 배포에서 백업 및 복구 서비스를 활성화하십시오.

.시작하기 전에
NetApp Backup and Recovery 라이선스를 취득했는지 확인하십시오. 자세한 내용은 https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-data-services-licenses.html#obtain-a-license-file["라이센스 취득"^]을 참조하십시오.

.단계
. NetApp Console 메뉴에서 *스토리지 > 플릿*을 선택합니다.
. 필요한 경우 *선박 추가*를 선택하여 함대 정보를 추가하십시오.
. *관리 > 라이선스*를 선택합니다.
. 백업 및 복구용 라이선스를 추가하려면 *라이선스 추가*를 선택하십시오. 라이선스 추가에 대한 자세한 내용은 https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-data-services-licenses.html#add-a-license["라이선스를 추가합니다"^]을 참조하십시오.
. *Storage* > *Fleets* 를 선택한 다음 *Systems* 메뉴를 엽니다.
. 시스템을 추가하려면 *추가*를 선택하고 시스템 세부 정보를 입력한 다음 *추가*를 선택하여 새 시스템을 저장하십시오.
. 시스템을 선택하고 클러스터를 선택하십시오. 페이지 오른쪽 정보 패널에서 백업 및 복구 서비스의 *활성화* 버튼을 선택하십시오.
. *백업 볼륨*을 선택합니다.
. *다음*을 선택하세요.
. 보호할 소스 볼륨을 선택하고 *다음*을 선택하십시오.
. 백업 전략 정의 페이지에서 백업 아키텍처를 선택한 다음 로컬 스냅샷, 복제 볼륨 및 백업 파일에 대한 정책 및 기타 세부 정보를 정의합니다. 이 시스템에서 처음 활성화한 볼륨의 백업 옵션에 대한 세부 정보를 참조하십시오. 그런 다음 *다음*을 선택합니다.
. 선택적으로 백업 및 복구 기능이 일치하지 않는 백업, 스냅샷 및 복제 레이블을 자동으로 수정하도록 설정할 수 있습니다.
. 이 볼륨의 백업 설정을 검토한 다음 *백업 활성화*를 선택합니다.
. 보호한 볼륨은 볼륨 개요 페이지에 표시됩니다.

