---
sidebar: sidebar 
permalink: br-start-configure-oracle-database.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle, configure 
summary: NetApp Backup and Recovery에서 Oracle 데이터베이스를 구성하십시오. 
---
= NetApp Backup and Recovery에서 Oracle 데이터베이스 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
새로운 독립형 또는 클러스터형 Oracle 데이터베이스에 대한 인증 및 노드 설정을 변경할 수 있습니다. NetApp Backup and Recovery는 이러한 변경 사항 없이 데이터베이스를 보호합니다. 검색 후 환경이 변경되면 데이터베이스 설정을 업데이트해야 할 수 있습니다.

*필수 콘솔 역할* 백업 및 복구 슈퍼 관리자.  에 대해 알아보세요link:reference-roles.html["백업 및 복구 역할과 권한"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp Console 액세스 역할에 대해 알아보세요."^] .



== Oracle 데이터베이스 구성

독립형 또는 클러스터형 Oracle 데이터베이스의 구성을 변경합니다.

.단계
. NetApp Console 메뉴에서 *보호 > 백업 및 복구*를 선택합니다.
. *워크로드*에서 *Oracle* 타일을 선택하십시오.
. Oracle 인벤토리에서 *Databases* 메뉴를 선택합니다.
. 데이터베이스 목록에서 구성하려는 데이터베이스에 대해 *Configure database*(독립 실행형 데이터베이스) 또는 *Configure RAC database*(클러스터형 데이터베이스)를 선택합니다.
. *데이터베이스 설정 구성*: 독립 실행형 또는 클러스터형 데이터베이스에 대한 인증 설정을 구성합니다.
+
** 호스트 운영 체제로만 인증하려면 *OS 인증*을 선택하십시오. Backup and Recovery는 검색 중에 지정한 호스트 자격 증명을 사용합니다.
** 데이터베이스에 자격 증명이 필요한 경우 *데이터베이스 인증*을 선택하십시오. 그런 다음 기존 자격 증명을 선택하거나 새 자격 증명을 추가하고 연결에 사용할 포트를 선택하십시오.


. *RMAN 카탈로그 구성*: 보호 정책에서 자동 카탈로그 생성이 활성화되었거나 복구 지점을 수동으로 카탈로그화할 때 이 데이터베이스 또는 클러스터의 백업 및 복구 작업에 대한 메타데이터가 저장되는 위치를 선택합니다.
+
** *대상 제어 파일*을 선택하여 데이터베이스 대상 제어 파일에 메타데이터를 저장합니다.
** RMAN 복구 카탈로그에 메타데이터를 저장하려면 * Catalog database * 를 선택합니다. 복구 카탈로그에 연결할 자격 증명 및 TNS(Transparent Network Substrate) 이름을 선택합니다.
+
RMAN 복구 카탈로그는 RMAN 유틸리티에서 등록된 데이터베이스의 백업 및 복구 작업에 대한 메타데이터를 저장하는 데 사용되는 별도의 데이터베이스 스키마입니다. 대상 제어 파일이 손실되거나 기간별 데이터가 필요한 경우를 대비하여 중복성과 장기 보존 기능을 제공합니다. 이 옵션을 활성화하면 데이터 파일 및 아카이브 로그 복사본이 RMAN 저장소에 등록되어 RMAN이 보고 및 복구를 위해 해당 복사본을 추적하고 관리할 수 있습니다.



. *노드 구성*(클러스터형 데이터베이스만 해당): 화살표 버튼을 사용하여 보호에서 노드를 추가 또는 제거하거나 노드 우선 순위를 변경합니다.
+
우선순위가 높은 노드부터 먼저 보호됩니다. 우선순위가 낮은 노드는 우선순위가 높은 노드에 접근할 수 없거나 비정상적인 경우에만 보호됩니다.

. 완료되면 * Done * 을 선택합니다.


.결과
NetApp Backup and Recovery는 새 설정을 사용하여 데이터베이스에 연결합니다.
