---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, NetApp Backup and Recovery frequently asked questions 
summary: 이 FAQ는 질문에 대한 빠른 답변을 찾는 데 도움이 될 수 있습니다. 
---
= NetApp 백업 및 복구에 대한 자주 묻는 질문
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
이 FAQ는 질문에 대한 빠른 답변을 찾는 데 도움이 될 수 있습니다.



== 전개

* NetApp Backup and Recovery 미리보기 버전을 사용하려면 라이선스가 필요합니까?*

다음 라이선스 유형을 사용할 수 있습니다.

* 30일 무료 체험판에 등록하세요.


* NetApp 백업 및 복구를 어떻게 활성화하나요?*  NetApp 백업 및 복구에는 어떠한 활성화도 필요하지 않습니다.  백업 및 복구 옵션은 콘솔 왼쪽 탐색에서 자동으로 활성화됩니다.

시작하려면 가입하거나 NetApp 영업 담당자에게 연락하여 백업 및 복구를 체험해 보세요. 그런 다음 콘솔 에이전트를 사용하면 서비스에 적합한 기능이 포함됩니다.

NetApp 백업 및 복구를 시작하려면 초기 랜딩 페이지에서 "워크로드 검색 시작"을 선택하세요.

* NetApp 백업 및 복구를 표준, 제한 및 개인 모드로 사용할 수 있나요?*  현재 NetApp Backup and Recovery는 표준 모드로만 제공됩니다.  더 많은 내용을 기대하세요.

모든 NetApp 데이터 서비스에서 이러한 모드에 대한 설명은 다음을 참조하세요. https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["NetApp 콘솔 배포 모드"^] .



== 입장

* NetApp 백업 및 복구 URL은 무엇인가요?* 브라우저에서 URL을 입력하세요. https://console.netapp.com/["https://console.netapp.com/backup-and-recovery"^] NetApp 콘솔에 액세스합니다.

*접근 권한은 어떻게 처리되나요?*  조직 관리자만이 서비스를 시작하고 작업 부하를 검색할 수 있는 권한을 가지고 있습니다(이는 리소스 사용에 대한 커밋을 포함하기 때문입니다).  이후의 상호작용은 어떤 역할에 의해서도 수행될 수 있습니다.

*어떤 기기에 가장 적합한 해상도가 있나요?*  NetApp 백업 및 복구에 권장되는 장치 해상도는 1920x1080 이상입니다.

*어떤 브라우저를 사용해야 하나요?* 모든 최신 브라우저에서 작동합니다.



== 다른 서비스와의 상호 작용

* NetApp Backup and Recovery는 NetApp ONTAP 에서 설정된 보호 설정을 인식합니까?*  네, NetApp Backup and Recovery는 ONTAP 에 설정된 스냅샷 일정을 검색합니다.

* NetApp Backup and Recovery 사용하여 정책을 설정한 경우, 향후 변경 사항은 Backup and Recovery에서만 적용해야 합니까?* NetApp Backup and Recovery에서 정책을 변경하는 것이 좋습니다.



== 작업 부하

*작업량은 무엇으로 구성되나요?*  워크로드는 Preview 2025 버전에 대한 애플리케이션입니다.  작업 부하에는 단일 애플리케이션 인스턴스에서 사용되는 모든 볼륨이 포함됩니다.  예를 들어, mssql3.host.com에 배포된 Microsoft SQL Server DB 인스턴스는 각각 데이터와 로그에 대해 vol1과 vol2를 가질 수 있습니다.  이러한 볼륨은 함께 해당 DB 인스턴스의 특정 인스턴스에 대한 작업 부하를 구성합니다.

* NetApp Backup and Recovery는 어떤 워크로드를 지원합니까?*

Preview 2025 버전의 경우 NetApp Backup and Recovery는 다음 워크로드를 식별할 수 있습니다. Microsoft SQL Server 애플리케이션.

*"보호된" 작업 부하란 무엇입니까?*  NetApp 백업 및 복구에서 워크로드에 기본 감지 정책이 활성화된 경우 해당 워크로드는 "보호됨" 상태로 표시됩니다.

*"위험에 처한" 작업 부하란 무엇입니까?*  워크로드에 기본 감지 정책이 활성화되어 있지 않으면 백업 및 스냅샷 정책이 활성화되어 있어도 "위험에 처해 있습니다".

*새로운 워크로드가 추가되었지만 아직 나타나지 않음* 환경에 새로운 워크로드를 추가한 경우 검색을 다시 시작하고 보호 정책을 적용하여 새 리소스를 보호합니다.



== 보호 정책

* NetApp Backup and Recovery는 NetApp ONTAP 에서 설정된 보호 설정을 인식합니까?*

네, NetApp Backup and Recovery는 ONTAP 에 설정된 스냅샷 일정을 검색하고 검색된 워크로드에서 ARP 및 FPolicy가 활성화되어 있는지 여부를 검색합니다.  대시보드에 처음 표시되는 정보는 다른 NetApp 솔루션과 제품에서 집계된 것입니다.

* NetApp Backup and Recovery는 SnapCenter 에서 이미 만들어진 정책을 알고 있나요?*

네, SnapCenter 에서 관리되는 워크로드가 있는 경우 해당 제품에서 관리하는 정책이 NetApp Backup and Recovery로 적용됩니다.

* SnapCenter 에서 가져온 정책을 수정할 수 있나요?*

네, NetApp Backup and Recovery 내에서 SnapCenter 에서 관리하던 정책을 수정할 수 있습니다.

* ONTAP 의 정책(ARP, FPolicy, 스냅샷 등 System Manager에서 이미 활성화된 정책)이 있는 경우 NetApp Backup and Recovery에서 해당 정책이 변경됩니까?*

아니요. NetApp Backup and Recovery는 ONTAP 의 기존 탐지 정책(ARP, FPolicy 설정)을 수정하지 않습니다.

* NetApp Backup and Recovery에 가입한 후 SnapCenter 에 새로운 정책을 추가하면 어떻게 되나요?*

NetApp 백업 및 복구는 SnapCenter 에서 생성된 모든 새로운 정책을 인식합니다.

* ONTAP 에서 정책을 변경할 수 있나요?*

네, NetApp Backup and Recovery에서 ONTAP 의 정책을 변경할 수 있습니다.  NetApp Backup and Recovery에서 새로운 정책을 만들어 워크로드에 적용할 수도 있습니다.  이 작업을 수행하면 기존 ONTAP 정책이 NetApp Backup and Recovery에서 생성된 정책으로 바뀝니다.
