---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: NetApp Backup and Recovery를 사용하기 전에 몇 가지 단계를 수행하여 백업 대상을 설정하세요. 
---
= NetApp Backup and Recovery를 사용하기 전에 백업 대상을 설정하세요.
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery를 사용하기 전에 몇 가지 단계를 수행하여 백업 대상을 설정하세요.

시작하기 전에 검토하세요link:concept-start-prereq.html["전제 조건"] 귀하의 환경이 준비되었는지 확인하세요.



== 백업 대상을 준비하세요

다음 백업 대상 중 하나 이상을 준비하세요.

* NetApp StorageGRID.
+
참조하다 https://docs.netapp.com/us-en/storage-management-storagegrid/task-discover-storagegrid.html["StorageGRID 알아보세요"^] .

+
참조하다 https://docs.netapp.com/us-en/storagegrid/index.html["StorageGRID 문서"^] StorageGRID 에 대한 자세한 내용은 다음을 참조하세요.

* 아마존 웹 서비스. 참조하다 https://docs.netapp.com/us-en/storage-management-s3-storage/index.html["Amazon S3 문서"^] .
+
AWS를 백업 대상으로 준비하려면 다음을 수행하세요.

+
** AWS에 계정을 설정합니다.
** 다음 섹션에 나열된 AWS에서 S3 권한을 구성합니다.
** 콘솔에서 AWS 스토리지를 관리하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["Amazon S3 버킷 관리"^] .




* 마이크로소프트 애저.
+
** 참조하다 https://docs.netapp.com/us-en/storage-management-azure-netapp-files/index.html["Azure NetApp Files 설명서"^] .
** Azure에 계정을 설정합니다.
** 구성 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Azure 권한"^] Azure에서.
** 콘솔에서 Azure 저장소를 관리하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["Azure 저장소 계정 관리"^] .




백업 대상지 자체에서 옵션을 구성한 후 나중에 NetApp Backup and Recovery에서 백업 대상으로 구성하게 됩니다.  NetApp Backup and Recovery에서 백업 대상을 구성하는 방법에 대한 자세한 내용은 다음을 참조하세요.link:br-start-discover-backup-targets.html["백업 대상 검색"] .



== S3 권한 설정

AWS S3 권한 두 세트를 구성해야 합니다.

* 콘솔 에이전트가 S3 버킷을 생성하고 관리할 수 있는 권한입니다.
* 온프레미스 ONTAP 클러스터가 S3 버킷에서 데이터를 읽고 쓸 수 있는 권한입니다.


.단계
. 콘솔 에이전트에 필요한 권한이 있는지 확인하세요. 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-aws.html["NetApp 콘솔 정책 권한"] .
+

NOTE: AWS 중국 리전에서 백업을 생성할 때 IAM 정책의 모든 _Resource_ 섹션 아래에 있는 AWS 리소스 이름 "arn"을 "aws"에서 "aws-cn"으로 변경해야 합니다. 예를 들어, `arn:aws-cn:s3:::netapp-backup-*` .

. 서비스를 활성화하면 백업 마법사가 액세스 키와 비밀 키를 입력하라는 메시지를 표시합니다.  이러한 자격 증명은 ONTAP 클러스터에 전달되어 ONTAP S3 버킷에 데이터를 백업하고 복원할 수 있도록 합니다.  이를 위해서는 다음 권한이 있는 IAM 사용자를 만들어야 합니다.
+
를 참조하세요 https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["AWS 설명서: IAM 사용자에게 권한을 위임하는 역할 생성"^] .

+
[%collapsible]
====
[source, json]
----
{
    "Version": "2012-10-17",
     "Statement": [
        {
           "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow",
            "Sid": "backupPolicy"
        },
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListAllMyBuckets",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:RestoreObject",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetObjectRetention",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutObjectRetention"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*/*",
            "Effect": "Allow"
        }
    ]
}
----
====

