---
sidebar: sidebar 
permalink: br-use-hyperv-restore.html 
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery 
summary: NetApp Backup and Recovery 통해 Hyper-V 워크로드를 보호하세요. 
---
= NetApp Backup and Recovery 사용하여 Hyper-V 워크로드 복원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 사용하여 스냅샷, 보조 스토리지에 복제된 워크로드 백업 또는 개체 스토리지에 저장된 백업에서 Hyper-V 워크로드를 복원합니다.

.이 위치에서 복원
다양한 시작 위치에서 작업 부하를 복원할 수 있습니다.

* 기본 위치(로컬 스냅샷)에서 복원
* 보조 저장소의 복제된 리소스에서 복원
* 개체 스토리지 백업에서 복원


.이 지점으로 복원
다음 지점으로 데이터를 복원할 수 있습니다.

* 원래 위치로 복원


.개체 저장소 고려 사항에서 복원
개체 스토리지에서 백업 파일을 선택하고 해당 백업에 대해 랜섬웨어 보호가 활성화된 경우(백업 정책에서 DataLock 및 랜섬웨어 복원력을 활성화한 경우), 데이터를 복원하기 전에 백업 파일에 대한 추가 무결성 검사를 실행하라는 메시지가 표시됩니다.  검사를 실시해 보시기 바랍니다.


TIP: 백업 파일의 내용에 액세스하려면 클라우드 제공업체로부터 추가적인 퇴장 비용이 발생합니다.



== 워크로드 복원 작동 방식

작업 부하를 복원하면 다음이 발생합니다.

* 로컬 백업 파일에서 워크로드를 복원하면 NetApp Backup and Recovery 백업의 데이터를 사용하여 _새로운_ 리소스를 만듭니다.
* 복제된 워크로드에서 복원하는 경우 워크로드를 원래 시스템이나 온프레미스 ONTAP 시스템으로 복원할 수 있습니다.


복원 페이지(검색 및 복원이라고도 함)*에서는 정확한 이름, 리소스가 있는 위치 또는 마지막으로 양호한 상태였던 날짜를 기억하지 못하더라도 리소스를 복원할 수 있습니다. 필터를 사용하여 스냅샷을 검색할 수 있습니다.



== 복원 옵션(검색 및 복원)에서 작업 부하 데이터 복원

복원 옵션을 사용하여 Hyper-V 워크로드를 복원합니다. 스냅샷을 이름이나 필터를 사용하여 검색할 수 있습니다.

*필수 콘솔 역할* 백업 및 복구 슈퍼 관리자 또는 백업 및 복구 복원 관리자 역할. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp Console 액세스 역할에 대해 알아보세요."^] .

.단계
. NetApp Backup and Recovery 메뉴에서 *복원*을 선택합니다.
. 이름 검색 필드 오른쪽에 있는 드롭다운 목록에서 *Hyper-V*를 선택합니다.
. 복원하려는 리소스의 이름을 입력하거나 복원하려는 리소스가 있는 VM 이름, VM 호스트 또는 스토리지 풀로 필터링합니다.
+
검색 기준에 맞는 스냅샷 목록이 나타납니다.

. 복원하려는 스냅샷의 *복원* 버튼을 선택하세요.
+
가능한 복원 지점 목록이 나타납니다.

. 사용할 복원 지점을 선택하세요.
. 스냅샷 소스 위치를 선택하세요.
. 계속하려면 *다음*을 선택하세요.
. 복원 대상 및 설정을 선택하십시오.


[discrete]
===== 목적지 선택

[role="tabbed-block"]
====
.원래 위치로 복원
--
원래 위치로 복원하면 *대상 설정* 섹션을 확장하여 대상 설정을 볼 수 있지만 변경할 수는 없습니다.

. *복원 후 옵션* 섹션에서 다음 옵션을 고려하십시오.
+
*가상 머신 재시작*: 복원 후 새 가상 머신을 부팅하려면 이 옵션을 활성화하십시오.

. *복원*을 선택하세요.


--
.대체 위치로 복원
--
Hyper-V 워크로드 미리 보기에서는 사용할 수 없습니다.

--
====