---
sidebar: sidebar 
permalink: br-use-vmware-restore-guest-files-and-folders-overview.html 
keywords:  
summary: 'Windows 게스트 OS의 가상 머신 디스크(VMDK)에서 파일이나 폴더를 복원할 수 있습니다.' 
---
= 게스트 파일 및 폴더 복원 시 요구 사항 및 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Windows 게스트 OS의 가상 머신 디스크(VMDK)에서 파일이나 폴더를 복원할 수 있습니다.



== 게스트 복원 워크플로

게스트 OS 복원 작업에는 다음 단계가 포함됩니다.

. 붙이다
+
게스트 VM에 가상 디스크를 연결하고 게스트 파일 복원 세션을 시작합니다.

. 기다리다
+
연결 작업이 완료될 때까지 기다린 후 찾아보기 및 복원 작업을 진행하십시오. 연결 작업이 완료되면 게스트 파일 복원 세션이 자동으로 생성됩니다.

. 파일 또는 폴더 선택
+
VMDK 파일을 찾아보고 복원할 파일 또는 폴더를 하나 이상 선택하십시오.

. 복원하다
+
선택한 파일이나 폴더를 지정된 위치로 복원합니다.





== 게스트 파일 및 폴더 복원을 위한 전제 조건

Windows 게스트 운영 체제에서 VMDK 파일의 파일이나 폴더를 복원하기 전에 모든 요구 사항을 검토하십시오.

* VMware 도구가 설치되어 실행 중이어야 합니다.
+
NetApp Backup and Recovery VMware 도구의 정보를 사용하여 VMware 게스트 운영 체제에 연결을 설정합니다.

* Windows 게스트 운영 체제는 Windows Server 2008 R2 이상이어야 합니다.
+
지원되는 버전에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구(IMT)"^] .

* 대상 VM에 대한 자격 증명은 사용자 이름이 "Administrator"인 내장 도메인 또는 로컬 관리자 계정을 사용합니다. 복원 작업을 시작하기 전에 가상 디스크를 연결할 VM에 대한 자격 증명을 구성하십시오. 연결 및 복원 작업 모두에 자격 증명이 필요합니다. 워크그룹 사용자는 내장된 로컬 관리자 계정을 사용할 수 있습니다.
+

IMPORTANT: 기본 관리자 계정이 아니지만 VM 내에서 관리자 권한이 있는 계정을 사용해야 하는 경우 게스트 VM에서 UAC를 비활성화해야 합니다.

* 복원할 백업 스냅샷과 VMDK를 알아야 합니다.
+
NetApp Backup and Recovery 복원할 파일이나 폴더를 검색하는 기능을 지원하지 않습니다. 시작하기 전에 스냅샷과 해당 VMDK 파일에서 파일이나 폴더의 위치를 ​​알아야 합니다.

* 연결할 가상 디스크는 NetApp Backup and Recovery 백업에 포함되어 있어야 합니다.
+
복원하려는 파일 또는 폴더가 포함된 가상 디스크는 NetApp Backup and Recovery 사용하여 수행된 VM 백업에 있어야 합니다.



* 영어 알파벳이 아닌 이름을 가진 파일의 경우 단일 파일이 아닌 디렉토리에 복원해야 합니다.
+
일본어 간지와 같이 알파벳이 아닌 이름을 가진 파일은 해당 파일이 위치한 디렉토리를 복원하여 복원할 수 있습니다.





== 게스트 파일 복원 제한 사항

게스트 운영 체제에서 파일이나 폴더를 복원하기 전에 기능 제한 사항을 숙지해야 합니다.

* 게스트 OS 내부에서는 동적 디스크 유형을 복원할 수 없습니다.
* 암호화된 파일이나 폴더를 복원하면 암호화 속성이 유지되지 않습니다.
* 암호화된 폴더에는 파일이나 폴더를 복원할 수 없습니다.
* 숨겨진 파일과 폴더는 파일 탐색 페이지에 표시되지만 필터링할 수 없습니다.
* Linux 게스트 OS에서는 복원할 수 없습니다.
+
Linux 게스트 OS를 실행하는 VM에서는 파일과 폴더를 복원할 수 없습니다. 하지만 VMDK를 첨부한 다음 파일과 폴더를 수동으로 복원할 수 있습니다. 지원되는 게스트 OS에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 도구(IMT)"^] .

* NTFS 파일 시스템에서 FAT 파일 시스템으로 복원할 수 없습니다.
+
NTFS 포맷에서 FAT 포맷으로 복원하려고 하면 FAT 파일 시스템이 Windows 보안 속성을 지원하지 않기 때문에 NTFS 보안 설명자가 복사되지 않습니다.

* 복제된 VMDK나 초기화되지 않은 VMDK에서는 게스트 파일을 복원할 수 없습니다.
* 파일의 디렉토리 구조를 복원할 수 없습니다.
+
중첩된 디렉터리에서 파일을 복원할 때 시스템은 파일만 복원하고 디렉터리 구조는 복원하지 않습니다. 전체 디렉터리 트리를 복원하려면 최상위 디렉터리를 복사하십시오.

* vVol VM에서 다른 호스트로 게스트 파일을 복원할 수 없습니다.
* 암호화된 게스트 파일은 복구할 수 없습니다.

