---
sidebar: sidebar 
permalink: br-use-oracle-restore.html 
keywords: restore, vm, oracle, databases, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp 백업 및 복구를 통해 Oracle 워크로드를 보호하세요. 
---
= NetApp Backup and Recovery를 사용하여 Oracle 데이터베이스 복원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery를 사용하여 스냅샷 복사본, 보조 스토리지에 복제된 백업 또는 개체 스토리지에 저장된 백업에서 Oracle 데이터베이스를 복원합니다.

.이 위치에서 복원
다양한 시작 위치에서 데이터베이스를 복원할 수 있습니다.

* 기본 위치(로컬 스냅샷)에서 복원
* 보조 저장소의 복제된 리소스에서 복원
* 개체 스토리지 백업에서 복원


.이 지점으로 복원
원래 위치로 데이터를 복원할 수 있지만, 이 비공개 미리보기 릴리스에서는 대체 위치로 복원하는 기능을 사용할 수 없습니다.

* 원래 위치로 복원




== Oracle 데이터베이스 복원 작동 방식

Oracle 데이터베이스를 복원하면 다음이 발생합니다.

* 로컬 스냅샷에서 데이터베이스를 복원하면 NetApp Backup and Recovery는 백업의 데이터를 사용하여 _새로운_ 리소스를 만듭니다.
* 복제된 저장소에서 복원하면 원래 위치로 복원할 수 있습니다.
* 개체 스토리지에서 백업을 복원하면 데이터를 소스 스토리지나 온프레미스 ONTAP 시스템으로 복원하고 해당 위치에서 데이터베이스를 복구할 수 있습니다.


복원 페이지(검색 및 복원이라고도 함)에서는 정확한 이름, 데이터베이스가 있는 위치 또는 마지막으로 양호한 상태였던 날짜를 기억하지 못하더라도 데이터베이스를 복원할 수 있습니다.  필터를 사용하여 데이터베이스를 검색할 수 있습니다.



== Oracle 데이터베이스 복원

사용자의 요구 사항에 따라 Oracle 데이터베이스를 특정 시점, 특정 시스템 변경 번호(SCN) 또는 마지막 정상 상태로 복원합니다.  스냅샷에서 데이터베이스를 간단히 복원하고 자동 복구 프로세스를 건너뛸 수도 있습니다.  수동으로 복구를 수행하려면 자동 복구 프로세스를 건너뛸 수 있습니다.  데이터베이스 이름이나 특정 필터를 사용하여 데이터베이스를 검색할 수 있습니다.

*필수 콘솔 역할* 백업 및 복구 슈퍼 관리자 또는 백업 및 복구 복원 관리자 역할. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp 콘솔 액세스 역할에 대해 알아보세요."^] .

.단계
. NetApp 콘솔 메뉴에서 *보호 > 백업 및 복구*를 선택합니다.
. NetApp 백업 및 복구 메뉴에서 *복원*을 선택합니다.
. 이름 검색 필드 오른쪽에 있는 드롭다운 목록에서 *Oracle*을 선택합니다.
. 복원하려는 데이터베이스의 이름을 입력하거나 복원하려는 데이터베이스가 있는 데이터베이스 호스트를 필터링합니다.
+
검색 기준에 맞는 스냅샷 목록이 나타납니다.

. 복원하려는 데이터베이스에 대해 *복원* 버튼을 선택합니다.
. 복원 옵션을 선택하세요:
+
[role="tabbed-block"]
====
.특정 시점으로 복원
--
.. *특정 시점으로 복원*을 선택하세요.
.. *다음*을 선택하세요.
.. 드롭다운에서 날짜를 선택하고 *검색*을 선택하세요.
+
지정된 날짜에 일치하는 스냅샷 목록이 표시됩니다.



--
.특정 시스템 변경 번호(SCN)로 복원
--
.. *특정 시스템 변경 번호(SCN)로 복원*을 선택합니다.
.. *다음*을 선택하세요.
.. 복원 지점으로 사용할 SCN을 입력하고 *검색*을 선택합니다.
+
지정된 SCN에 맞는 스냅샷 목록이 표시됩니다.



--
.최신 백업(마지막 양호한 상태)으로 복원
--
.. *최신 백업으로 복원*을 선택하세요.
.. *다음*을 선택하세요.
+
최신 전체 백업과 로그 백업이 표시됩니다.



--
.복구 없이 스냅샷에서 복원
--
.. *복구 없이 스냅샷에서 복원*을 선택합니다.
.. *다음*을 선택하세요.
+
일치하는 스냅샷이 표시됩니다.



--
====
. 스냅샷 소스 위치를 선택하세요.
. *다음*을 선택하여 복원 대상 설정 페이지로 이동합니다.
+
다음으로, 대상 설정과 복원 전, 복원 후 옵션을 선택할 수 있습니다.



[discrete]
===== 목적지 선택

. 대상 설정과 복원 전, 복원 후 옵션을 선택하세요.


[role="tabbed-block"]
====
.원래 위치로 복원
--
. *목적지 설정*:
+
** 전체 데이터베이스를 복원할지 아니면 데이터베이스의 테이블스페이스만 복원할지 선택합니다.
** *제어 파일*: 선택적으로 이 옵션을 활성화하면 데이터베이스 제어 파일도 복원됩니다.


. *사전 복원 옵션*:
+
** 선택적으로, 이 옵션을 활성화하고 복원 작업 전에 실행해야 하는 스크립트의 전체 경로와 스크립트가 취하는 인수를 입력합니다.
** 스크립트에 대한 시간 초과 값을 선택하세요.  이 기간 내에 스크립트가 실행되지 않으면 복원은 계속 진행됩니다.


. *복원 후 옵션*:
+
** *추신*: 선택적으로 이 옵션을 활성화하고 복원 작업 이후에 실행되어야 하는 스크립트의 전체 경로와 스크립트가 취하는 인수를 입력합니다.
** *복구 후 읽기-쓰기 모드로 데이터베이스 또는 컨테이너 데이터베이스 열기*: 복원 작업이 완료되면 백업 및 복구가 데이터베이스에 대해 읽기-쓰기 모드를 활성화합니다.


. *알림* 섹션:
+
** *이메일 알림 사용*: 복구 작업에 대한 이메일 알림을 받으려면 이 옵션을 선택하고, 어떤 유형의 알림을 받을지 지정합니다.


. *복원*을 선택하세요.


--
.대체 위치로 복원
--
Oracle 워크로드 미리 보기에서는 사용할 수 없습니다.

--
====