---
sidebar: sidebar 
permalink: br-use-oracle-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 온프레미스 ONTAP 시스템부터 Amazon Web Services, Microsoft Azure, Google Cloud Platform, StorageGRID 까지 Oracle 가상 머신을 보호하여 데이터가 안전하게 보호되도록 할 수 있습니다. 
---
= Oracle Database 워크로드 보호 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery를 사용하여 Oracle 데이터베이스와 로그를 보호하세요. 빠르고 공간 효율적이며, 크래시 일관성 및 데이터베이스 일관성을 보장하는 백업 및 복원 기능을 제공합니다. Oracle Database 워크로드를 AWS S3, NetApp StorageGRID, Azure Blob Storage 또는 ONTAP S3에 백업하고, 온프레미스 Oracle 호스트에 복원할 수 있습니다.

NetApp Backup and Recovery 사용하여 3-2-1 보호 전략을 구현합니다. 즉, 소스 데이터의 사본 3개를 2개의 서로 다른 스토리지 시스템에 두고, 나머지 사본 1개를 클라우드에 둡니다. 3-2-1 접근 방식의 이점은 다음과 같습니다.

* 여러 개의 데이터 사본을 보관하여 내부 및 외부 사이버 보안 위협으로부터 보호합니다.
* 다양한 유형의 미디어를 사용하면 한 유형의 미디어가 실패하더라도 복구하는 데 도움이 됩니다.
* 온사이트 사본에서 빠르게 복원할 수 있으며, 온사이트 사본이 손상된 경우 오프사이트 사본을 사용할 수 있습니다.



NOTE: NetApp Backup and Recovery UI 버전으로 전환하려면 다음을 참조하세요.link:br-start-switch-ui.html["이전 NetApp Backup and Recovery UI로 전환"] .

NetApp Backup and Recovery를 사용하면 Oracle Database 워크로드와 관련된 다음과 같은 작업을 수행할 수 있습니다.

* link:br-start-discover-oracle.html["Oracle Database 워크로드를 살펴보세요"]
* link:br-use-oracle-protection-groups.html["Oracle Database 워크로드에 대한 보호 그룹 생성 및 관리"]
* link:br-use-oracle-backup.html["Oracle Database 워크로드를 백업합니다"]
* link:br-use-oracle-restore.html["Oracle Database 워크로드 복원"]

