---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: NetApp Backup and Recovery 사용하면 Kubernetes 애플리케이션과 관련 리소스의 보호를 해제하고 삭제할 수 있습니다. 
---
= Kubernetes 애플리케이션 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 사용하면 Kubernetes 애플리케이션과 관련 리소스의 보호를 해제하고 삭제할 수 있습니다.

.필수 NetApp Console 역할
조직 관리자 또는 SnapCenter 관리자. link:reference-roles.html["NetApp Backup and Recovery 액세스 역할에 대해 알아보세요"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp Console 액세스 역할에 대해 알아보세요."^] .



== Kubernetes 애플리케이션 보호 해제

더 이상 보호하고 싶지 않은 애플리케이션의 보호를 해제할 수 있습니다. 애플리케이션의 보호를 해제하면 NetApp Backup and Recovery 해당 애플리케이션의 보호를 중단하지만 연관된 모든 백업과 스냅샷은 보관합니다.

.단계
. NetApp Backup and Recovery 에서 *인벤토리*를 선택합니다.
. Kubernetes 인스턴스를 선택하고 *보기*를 선택하여 해당 인스턴스와 연결된 리소스를 확인합니다.
. *응용 프로그램* 탭을 선택하세요.
. 애플리케이션 목록에서 보호를 해제할 애플리케이션을 선택하고 관련된 작업 메뉴를 선택합니다.
. *보호 해제*를 선택하세요.
. 공지사항을 읽고 준비가 되면 *보호 해제*를 선택하세요.




== Kubernetes 애플리케이션 삭제

더 이상 필요 없는 애플리케이션을 삭제하세요.  NetApp Backup and Recovery 삭제된 애플리케이션의 보호를 중지하고 모든 백업과 스냅샷을 제거합니다.

.단계
. NetApp Backup and Recovery 에서 *인벤토리*를 선택합니다.
. Kubernetes 인스턴스를 선택하고 *보기*를 선택하여 해당 인스턴스와 연결된 리소스를 확인합니다.
. *응용 프로그램* 탭을 선택하세요.
. 애플리케이션 목록에서 삭제하려는 애플리케이션을 선택하고 관련된 작업 메뉴를 선택합니다.
. *삭제*를 선택하세요.
. *스냅샷 및 백업 삭제*를 활성화하면 애플리케이션의 모든 스냅샷과 백업이 제거됩니다.
+

CAUTION: 이러한 스냅샷과 백업을 사용하여 더 이상 애플리케이션을 복원할 수 없습니다.

. 작업을 확인하고 *삭제*를 선택하세요.

