---
sidebar: sidebar 
permalink: br-use-dashboard.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, backup, recovery, dashboard, view, health, status, alerts, notifications 
summary: 워크로드 상태를 모니터링하면 워크로드 보호에 문제가 있는지 파악하고 이를 해결하기 위한 조치를 취할 수 있습니다.  NetApp Backup and Recovery 대시보드에 나타나는 백업 및 복원 상태를 보고 알림에 대응하세요.  보호 요약, 복원 요약, 시스템 요약 등을 검토할 수 있습니다. 
---
= 백업 및 복구 대시보드에서 보호 상태 보기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
워크로드의 상태를 모니터링하여 보호 문제를 식별하고 경고에 대응하십시오. NetApp Backup and Recovery 대시보드에서 백업 및 복원 상태를 확인하고 시스템, 보호, 작업 및 복원 요약을 검토할 수 있습니다.

*필수 NetApp Console 역할* Backup and Recovery 슈퍼 관리자, Backup and Recovery 백업 관리자, Backup and Recovery 복원 관리자, Backup and Recovery 클론 관리자 또는 Backup and Recovery 백업 뷰어 역할. Cloud Volumes ONTAP 클러스터에 저장된 데이터를 보호하는 경우 Cloud Volumes ONTAP 관리자 역할도 필요합니다. 다음에 대해 알아보십시오. link:reference-roles.html["백업 및 복구 역할 및 권한"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp Console 액세스 역할에 대해 알아보세요."^].

.단계
. NetApp 콘솔 메뉴에서 *보호* > *백업 및 복구*를 선택합니다.
. 워크로드 타일(예: Microsoft SQL Server)을 선택합니다.
. 백업 및 복구 메뉴에서 *대시보드*를 선택합니다.
+
다음 유형의 정보를 검토할 수 있습니다.

+
** 발견된 호스트 또는 VM 수
** 발견된 Kubernetes 클러스터 수
** 개체 스토리지의 백업 대상 수
** vCenter 수
** ONTAP 의 스토리지 클러스터 수






[[view-the-protection-summary]]
== 보호 요약 보기

보호 요약에서 다음 정보를 검토하세요.

* 보호된 데이터베이스, VM, 데이터 저장소와 보호되지 않은 데이터베이스, VM, 데이터 저장소의 총 수입니다.
+

TIP: 보호된 데이터베이스는 백업 정책이 할당된 데이터베이스입니다.  보호되지 않은 데이터베이스란 백업 정책이 할당되지 않은 데이터베이스를 말합니다.

* 성공한 백업, 경고가 발생한 백업 또는 실패한 백업의 수입니다.
* 백업 서비스에서 발견한 총 용량과 보호되는 용량과 보호되지 않는 용량입니다.  자세한 내용을 보려면 "*i*" 아이콘 위에 마우스를 올려 놓으세요.




[[view-the-job-summary]]
== 직무 요약 보기

작업 요약에서 완료된 작업, 실행 중인 작업 또는 실패한 작업의 총 수를 확인하십시오.

.단계
. 각 작업 배포에 대해 필터를 변경하여 지난 30일, 지난 7일, 지난 24시간 또는 지난 1년 등 기간을 기준으로 실패한 작업, 실행 중인 작업 및 완료된 작업의 요약을 표시합니다.
. 실패한 작업, 실행 중인 작업 및 완료된 작업에 대한 자세한 내용을 보려면 *작업 모니터링 보기*를 선택하십시오.




[[view-the-restore-summary]]
== 복원 요약 보기

복원 요약에서 다음 정보를 검토하십시오.

* 수행된 복원 작업의 총 수
* 복구된 총 용량
* 로컬, 보조 및 개체 스토리지에서 수행된 복원 작업의 수입니다.  자세한 내용을 보려면 차트 위에 마우스를 올려 놓으세요.

