---
sidebar: sidebar 
permalink: br-use-protect-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: NetApp Backup and Recovery 사용하면 워크로드 호스트 정보, 데이터베이스 정보, 인스턴스 정보를 관리할 수 있습니다.  인벤토리에 대한 보호 설정을 보고, 편집하고, 삭제할 수 있습니다. 
---
= Kubernetes 애플리케이션 추가 및 보호
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 사용하면 kubeconfig 파일을 생성하고 업로드하지 않고도 Kubernetes 클러스터를 쉽게 검색할 수 있습니다.  NetApp Console 사용자 인터페이스에서 복사한 간단한 명령을 사용하여 Kubernetes 클러스터를 연결하고 필요한 소프트웨어를 설치할 수 있습니다.

.필수 NetApp Console 역할
조직 관리자 또는 SnapCenter 관리자. link:reference-roles.html["NetApp Backup and Recovery 액세스 역할에 대해 알아보세요"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp Console 액세스 역할에 대해 알아보세요."^] .



== 새로운 Kubernetes 애플리케이션 추가 및 보호

Kubernetes 애플리케이션을 보호하는 첫 번째 단계는 NetApp Backup and Recovery 내에서 애플리케이션을 만드는 것입니다.  애플리케이션을 만들면 Kubernetes 클러스터에서 실행 중인 애플리케이션을 콘솔에 알리게 됩니다.

.시작하기 전에
Kubernetes 애플리케이션을 추가하고 보호하려면 다음이 필요합니다.link:br-start-discover.html["Kubernetes 워크로드 검색"] .

.단계
. NetApp Backup and Recovery 에서 *인벤토리*를 선택합니다.
. Kubernetes 인스턴스를 선택하고 *보기*를 선택하여 해당 인스턴스와 연결된 리소스를 확인합니다.
. *응용 프로그램* 탭을 선택하세요.
. *애플리케이션 만들기*를 선택하세요.
. 애플리케이션의 이름을 입력하세요.
. 선택적으로 다음 필드 중 하나를 선택하여 보호하려는 리소스를 검색하세요.
+
** 연관된 클러스터
** 연관된 네임스페이스
** 리소스 유형
** 라벨 선택기


. 선택적으로, 클러스터 수준에서 범위가 지정된 리소스를 선택하려면 *클러스터 범위 리소스*를 선택합니다. 이 리소스를 포함하면 애플리케이션을 생성할 때 해당 리소스가 애플리케이션에 추가됩니다.
. 선택적으로 *검색*을 선택하여 검색 기준에 따라 리소스를 찾으세요.
+

NOTE: 콘솔은 검색 매개변수나 결과를 저장하지 않습니다. 매개변수는 애플리케이션에 포함될 수 있는 리소스를 선택한 Kubernetes 클러스터에서 검색하는 데 사용됩니다.

. 콘솔에는 검색 기준과 일치하는 리소스 목록이 표시됩니다.
. 보호하려는 리소스가 목록에 포함되어 있으면 *다음*을 선택합니다.
. 선택적으로, *정책* 영역에서 기존 보호 정책을 선택하여 애플리케이션을 보호하거나 새 정책을 만들 수 있습니다. 정책을 선택하지 않으면 애플리케이션은 보호 정책 없이 생성됩니다. 당신은 할 수 있습니다link:br-use-policies-create.html#create-a-policy["보호 정책 추가"] 나중에.
. *Prescripts and postscripts* 영역에서 백업 작업 전이나 후에 실행하려는 Prescripts 또는 Postscripts 실행 후크를 활성화하고 구성합니다.  사전 스크립트 또는 사후 스크립트를 활성화하려면 이미 하나 이상을 만들어야 합니다.link:br-use-manage-execution-hook-templates.html["실행 후크 템플릿"] .
. *만들기*를 선택하세요.


.결과
애플리케이션이 생성되어 Kubernetes 인벤토리의 *애플리케이션* 탭에 있는 애플리케이션 목록에 나타납니다.  NetApp Console 사용하면 설정에 따라 애플리케이션을 보호할 수 있으며, 백업 및 복구의 *모니터링* 영역에서 진행 상황을 모니터링할 수 있습니다.



== 기존 Kubernetes 애플리케이션 보호

이미 추가한 Kubernetes 애플리케이션에서 보호 정책을 활성화합니다.

.단계
. NetApp Backup and Recovery 에서 *인벤토리*를 선택합니다.
. Kubernetes 인스턴스를 선택하고 *보기*를 선택하여 해당 인스턴스와 연결된 리소스를 확인합니다.
. *응용 프로그램* 탭을 선택하세요.
. 애플리케이션 목록에서 보호하려는 애플리케이션을 선택하고 관련된 작업 메뉴를 선택합니다.
. *보호*를 선택하세요.
. *정책* 영역에서 애플리케이션을 보호하기 위한 기존 보호 정책을 선택하거나 새 정책을 만듭니다. 참조하다link:br-use-policies-create.html#create-a-policy["정책 만들기"] 보호 정책 생성에 대한 자세한 내용은 다음을 참조하세요.
. *Prescripts and postscripts* 영역에서 백업 작업 전이나 후에 실행하려는 Prescripts 또는 Postscripts 실행 후크를 활성화하고 구성합니다.  실행 후크의 유형, 사용하는 템플릿, 인수 및 레이블 선택기를 구성할 수 있습니다.
. *완료*를 선택하세요.


.결과
콘솔을 사용하면 설정에 따라 애플리케이션을 보호할 수 있으며, 백업 및 복구의 *모니터링* 영역에서 진행 상황을 모니터링할 수 있습니다.  애플리케이션에 대한 보호 기능을 활성화하면 콘솔에서 해당 애플리케이션의 전체 백업이 생성됩니다. 이후 증분 백업은 애플리케이션과 관련된 보호 정책에 정의된 일정에 따라 생성됩니다.



== 지금 Kubernetes 애플리케이션을 백업하세요

향후 백업 및 스냅샷을 위한 기준을 설정하거나 최신 데이터가 보호되도록 Kubernetes 애플리케이션의 백업을 수동으로 생성합니다.

.단계
. NetApp Backup and Recovery 에서 *인벤토리*를 선택합니다.
. Kubernetes 인스턴스를 선택하고 *보기*를 선택하여 해당 인스턴스와 연결된 리소스를 확인합니다.
. *응용 프로그램* 탭을 선택하세요.
. 애플리케이션 목록에서 백업하려는 애플리케이션을 선택하고 관련된 작업 메뉴를 선택합니다.
. *지금 백업*을 선택하세요.
. 올바른 애플리케이션 이름이 선택되었는지 확인하세요.
. *백업*을 선택하세요.


.결과
콘솔은 애플리케이션의 백업을 생성하고 백업 및 복구의 *모니터링* 영역에 진행 상황을 표시합니다. 백업은 애플리케이션과 연결된 보호 정책을 기반으로 생성됩니다.
