---
sidebar: sidebar 
permalink: br-use-dashboard.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, backup, recovery, dashboard, view, health, status, alerts, notifications 
summary: 워크로드 상태를 모니터링하면 워크로드 보호에 문제가 있는지 파악하고 이를 해결하기 위한 조치를 취할 수 있습니다.  NetApp 백업 및 복구 대시보드에 나타나는 백업 및 복원 상태를 보고 알림에 대응하세요.  보호 요약, 복원 요약, 시스템 요약 등을 검토할 수 있습니다. 
---
= NetApp 백업 및 복구 대시보드에서 보호 상태 보기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
워크로드 상태를 모니터링하면 워크로드 보호에 문제가 있는지 파악하고 이를 해결하기 위한 조치를 취할 수 있습니다.  NetApp 백업 및 복구 대시보드에서 백업 및 복원 상태를 확인하세요.  시스템 요약, 보호 요약, 작업 요약, 복원 요약 등을 검토할 수 있습니다.

*필수 NetApp 콘솔 역할* 스토리지 뷰어, 백업 및 복구 슈퍼 관리자, 백업 및 복구 백업 관리자, 백업 및 복구 복원 관리자, 백업 및 복구 복제 관리자 또는 백업 및 복구 뷰어 역할. 에 대해 알아보세요link:reference-roles.html["백업 및 복구 역할과 권한"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp 콘솔 액세스 역할에 대해 알아보세요."^] .

.단계
. NetApp 백업 및 복구 메뉴에서 *대시보드*를 선택합니다.
+
** 발견된 호스트 또는 VM 수
** 발견된 Kubernetes 클러스터 수
** 개체 스토리지의 백업 대상 수
** vCenter 수
** ONTAP 의 스토리지 클러스터 수






== 보호 요약 보기

보호 요약에서 다음 정보를 검토하세요.

* 보호된 데이터베이스, VM, 데이터 저장소와 보호되지 않은 데이터베이스, VM, 데이터 저장소의 총 수입니다.
+

TIP: 보호된 데이터베이스는 백업 정책이 할당된 데이터베이스입니다.  보호되지 않은 데이터베이스란 백업 정책이 할당되지 않은 데이터베이스를 말합니다.

* 성공한 백업, 경고가 발생한 백업 또는 실패한 백업의 수입니다.
* 백업 서비스에서 발견한 총 용량과 보호되는 용량과 보호되지 않는 용량입니다.  자세한 내용을 보려면 "*i*" 아이콘 위에 마우스를 올려 놓으세요.




== 직무 요약 보기

작업 요약에서 완료된 작업, 실행 중인 작업 또는 실패한 작업의 총계를 검토합니다.

.단계
. 각 작업 분포에 대해 실패, 실행 중, 완료에 대한 요약을 일수에 따라 표시하도록 필터를 변경합니다. 예를 들어, 지난 30일, 지난 7일, 지난 24시간, 지난 1년 등을 지정할 수 있습니다.
. *작업 모니터링 보기*를 선택하면 실패한 작업, 실행 중인 작업, 완료된 작업에 대한 세부 정보를 볼 수 있습니다.




== 복원 요약 보기

복원 요약에서 다음 정보를 검토하세요.

* 수행된 복원 작업의 총 수
* 복구된 총 용량
* 로컬, 보조 및 개체 스토리지에서 수행된 복원 작업의 수입니다.  자세한 내용을 보려면 차트 위에 마우스를 올려 놓으세요.

