---
sidebar: sidebar 
permalink: br-use-vmware-restore-vmdks-from-backups.html 
keywords:  
summary: 기존 VMDK를 복원하거나, 삭제되거나 분리된 VMDK를 기존 VM 또는 vVol VM의 기본 또는 보조 백업에서 복원할 수 있습니다. 
---
= 백업에서 특정 가상 디스크 복원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
기존 가상 디스크(VMDK) 또는 삭제되거나 분리된 가상 디스크를 기존 VM의 기본 또는 보조 백업에서 복원할 수 있습니다. 이를 통해 특정 VM 데이터나 애플리케이션만 복원할 수 있으므로 특정 데이터만 영향을 받는 상황에서 전체 VM과 관련된 모든 가상 디스크를 복원할 필요가 없습니다. 가상 디스크가 복원되면 원래 VM에 연결되어 사용할 준비가 됩니다.

VM에서 하나 이상의 가상 머신 디스크(VMDK)를 동일한 데이터 저장소 또는 다른 데이터 저장소로 복원할 수 있습니다.


TIP: NFS 환경에서 복원 작업의 성능을 향상시키려면 VMware 애플리케이션 vStorage API for Array Integration(VAAI)을 활성화하세요.

.시작하기 전에
* 백업이 반드시 존재해야 합니다.
* VM은 전송 중이어서는 안 됩니다.
+
복원하려는 VM은 vMotion 또는 Storage vMotion 상태가 아니어야 합니다.



.이 작업에 관하여
* VMDK가 삭제되거나 VM에서 분리되면 복원 작업을 통해 VMDK가 VM에 연결됩니다.
* VM이 있는 FabricPool 의 스토리지 계층을 사용할 수 없는 경우 복원 작업이 실패할 수 있습니다.
* 연결 및 복원 작업은 기본 SCSi 컨트롤러를 사용하여 VMDK를 연결합니다. 그러나 NVMe 디스크가 있는 VM에 연결된 VMDK를 백업하는 경우, 연결 및 복원 작업에는 NVMe 컨트롤러가 사용 가능한 경우 이를 사용합니다.


.단계
. NetApp Backup and Recovery 메뉴에서 *복원*을 선택합니다.
. 이름 검색 필드 오른쪽에 있는 드롭다운 목록에서 *VMware*를 선택합니다.
. 복원하려는 리소스의 이름을 입력하거나 복원하려는 리소스가 있는 vCenter, 데이터 센터 또는 데이터 저장소를 필터링합니다.
+
검색 기준과 일치하는 가상 머신 목록이 나타납니다.

. 목록에서 복원하려는 VM을 찾은 후 해당 VM의 옵션 메뉴 버튼을 선택합니다.
. 결과 메뉴에서 *가상 디스크 복원*을 선택합니다.
+
해당 가상 머신에 생성된 스냅샷(복원 지점) 목록이 나타납니다. 기본적으로, *시간 프레임* 드롭다운에서 선택한 기간의 최신 스냅샷이 표시됩니다.

+
각 스냅샷의 *위치* 열에 있는 켜진 아이콘은 스냅샷을 사용할 수 있는 저장 위치(기본, 보조 또는 개체 저장소)를 나타냅니다.

. 복원하려는 스냅샷에 대한 라디오 버튼을 활성화합니다.
. *다음*을 선택하세요.
+
스냅샷 위치 옵션이 나타납니다.

. 스냅샷의 복원 대상을 선택하세요.
+
** *로컬*: 로컬 위치에서 스냅샷을 복원합니다.
** *보조*: 원격 저장 위치에서 스냅샷을 복원합니다.
** *객체 저장소*: 개체 저장소에서 스냅샷을 복원합니다.
+
보조 저장소를 선택하는 경우 드롭다운 목록에서 대상 위치를 선택하세요.



. 계속하려면 *다음*을 선택하세요.
. 복원 대상 및 설정을 선택하십시오.


[discrete]
===== 목적지 선택

[role="tabbed-block"]
====
.원래 위치로 복원
--
원래 위치로 복원할 때 대상 vCenter, ESXi 호스트, 데이터 저장소 또는 가상 디스크 이름을 변경할 수 없습니다. 원본 가상 디스크가 덮어씌워집니다.

. *원래 위치* 창을 선택하세요.
. *대상 설정* 섹션에서 복원하려는 가상 디스크의 확인란을 활성화합니다.
. 다음 옵션 중에서 선택하세요:
+
** *사전 복원 옵션* 섹션:
+
*** *사전 스크립트*: 복원 작업이 시작되기 전에 사용자 정의 스크립트를 실행하여 추가 작업을 자동화하려면 이 옵션을 활성화합니다. 실행해야 하는 스크립트의 전체 경로와 스크립트가 취하는 인수를 입력하세요.


** *복원 후 옵션* 섹션:
+
*** *추신*: 복원이 완료된 후 사용자 정의 스크립트를 실행하여 추가 작업을 자동화하려면 이 옵션을 활성화합니다. 실행해야 하는 스크립트의 전체 경로와 스크립트가 취하는 인수를 입력하세요.




. *복원*을 선택하세요.


--
.대체 위치로 복원
--
대체 위치로 복원할 때 대상 데이터 저장소를 변경할 수 있습니다. 복원 작업 후 가상 디스크는 선택한 데이터 저장소와 관계없이 원래 VM에 연결됩니다.

. *대체 위치* 창을 선택하세요.
. *대상 설정* 섹션에서 복원하려는 가상 디스크의 확인란을 활성화합니다.
. 선택한 모든 가상 디스크에 대해:
+
.. 가상 디스크에 대한 다른 데이터 저장소 복원 대상을 선택하려면 *데이터 저장소 선택*을 선택합니다.
.. *선택*을 선택하여 선택 사항을 확인하고 선택 창을 닫습니다.


. 다음 옵션 중에서 선택하세요:
+
** *사전 복원 옵션* 섹션:
+
*** *사전 스크립트*: 복원 작업이 시작되기 전에 사용자 정의 스크립트를 실행하여 추가 작업을 자동화하려면 이 옵션을 활성화합니다. 실행해야 하는 스크립트의 전체 경로와 스크립트가 취하는 인수를 입력하세요.


** *복원 후 옵션* 섹션:
+
*** *추신*: 복원이 완료된 후 사용자 정의 스크립트를 실행하여 추가 작업을 자동화하려면 이 옵션을 활성화합니다. 실행해야 하는 스크립트의 전체 경로와 스크립트가 취하는 인수를 입력하세요.




. *복원*을 선택하세요.


--
====