---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: NetApp Backup and Recovery 사용하여 온프레미스 ONTAP 시스템에서 Amazon Web Services, Microsoft Azure 또는 StorageGRID 로 Microsoft SQL Server 애플리케이션 데이터를 보호하세요. 
---
= NetApp Backup and Recovery 개요를 사용하여 Microsoft SQL 워크로드 보호
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 사용하여 온프레미스 ONTAP 시스템의 Microsoft SQL Server 애플리케이션 데이터를 AWS, Azure 또는 StorageGRID 로 백업하세요.  시스템은 귀하의 정책에 따라 클라우드 계정에 자동으로 백업을 생성하고 저장합니다.  3-2-1 전략을 사용하세요. 데이터 사본을 두 개의 저장 시스템에 세 개 보관하고, 나머지는 클라우드에 보관하세요.

3-2-1 접근 방식의 이점은 다음과 같습니다.

* 여러 개의 데이터 사본을 보관하여 내부 및 외부 사이버 보안 위협으로부터 보호합니다.
* 다양한 유형의 미디어를 사용하면 한 유형의 미디어가 실패하더라도 복구하는 데 도움이 됩니다.
* 온사이트 사본에서 빠르게 복원할 수 있으며, 온사이트 사본이 손상된 경우 오프사이트 사본을 사용할 수 있습니다.


NetApp Backup and Recovery NetApp SnapMirror 사용하여 스냅샷을 생성하고 이를 백업 위치로 전송하여 백업을 동기화합니다.

데이터를 보호하려면 다음을 수행하세요.

* link:concept-start-prereq-snapcenter-import.html["SnapCenter 에서 가져오는 경우 추가 항목 구성"]
* link:br-start-discover.html["Microsoft SQL Server 워크로드를 검색하고 선택적으로 SnapCenter 리소스를 가져옵니다."]
* link:br-use-mssql-backup.html["로컬 ONTAP 기본 스토리지의 로컬 스냅샷으로 워크로드 백업"]
* link:br-use-mssql-backup.html["ONTAP 보조 스토리지에 작업 부하 복제"]
* link:br-use-mssql-backup.html["개체 저장소 위치에 워크로드 백업"]
* link:br-use-mssql-backup.html["지금 워크로드를 백업하세요"]
* link:br-use-mssql-restore.html["작업 부하 복원"]
* link:br-use-mssql-clone.html["복제 워크로드"]
* link:br-use-manage-inventory.html["작업량 인벤토리 관리"]
* link:br-use-manage-snapshots.html["스냅샷 관리"]


작업 부하를 백업하려면 백업 및 복원 작업을 관리하는 정책을 만듭니다. 보다link:br-use-policies-create.html["정책 생성"] 자세한 내용은.

.지원되는 백업 대상
NetApp Backup and Recovery 사용하면 다음 소스 시스템의 Microsoft SQL Server 인스턴스와 데이터베이스를 퍼블릭 및 프라이빗 클라우드 공급자의 다음 보조 시스템과 개체 스토리지로 백업할 수 있습니다. 스냅샷은 소스 시스템에 저장됩니다.

[cols="33,33,33"]
|===
| 소스 시스템 | 2차 시스템(복제) | 대상 개체 저장소(백업) 


| AWS의 Cloud Volumes ONTAP | AWS 온프레미스 ONTAP 시스템의 Cloud Volumes ONTAP | 아마존 S3 ONTAP S3 


| Azure의 Cloud Volumes ONTAP | Azure 온프레미스 ONTAP 시스템의 Cloud Volumes ONTAP | Azure Blob ONTAP S3 


| 온프레미스 ONTAP 시스템 | Cloud Volumes ONTAP 온프레미스 ONTAP 시스템 | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | 해당 없음 
|===
.지원되는 복원 대상
기본 저장소나 보조 시스템(복제된 볼륨) 또는 개체 저장소(백업 파일)에 있는 백업에서 Microsoft SQL Server 인스턴스와 데이터베이스를 다음 시스템으로 복원할 수 있습니다. 스냅샷은 소스 시스템에 저장되며 동일한 시스템으로만 복원할 수 있습니다.

[cols="33,33,33"]
|===
2+| 백업 파일 위치에서 | 목적지 시스템 


| *객체 저장소(백업)* | *2차 시스템(복제)* |  


| 아마존 S3 | AWS 온프레미스 ONTAP 시스템의 Cloud Volumes ONTAP | AWS 온프레미스 ONTAP 시스템 ONTAP S3의 클라우드 볼륨 


| Azure Blob | Azure 온프레미스 ONTAP 시스템의 Cloud Volumes ONTAP | Azure 온프레미스 ONTAP 시스템 ONTAP S3의 ​​Cloud Volumes ONTAP 


| StorageGRID | Cloud Volumes ONTAP 온프레미스 ONTAP 시스템 | 온프레미스 ONTAP 시스템 ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | 해당 없음 
|===

NOTE: "사내 ONTAP 시스템"에 대한 참조에는 FAS 및 AFF 시스템이 포함됩니다.
