---
sidebar: sidebar 
permalink: br-use-oracle-restore.html 
keywords: restore, vm, oracle, databases, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp Backup and Recovery를 사용하여 Oracle 데이터베이스 워크로드를 보호하십시오. 
---
= NetApp Backup and Recovery를 사용하여 Oracle 데이터베이스 워크로드를 복원합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
스냅샷, 2차 스토리지의 복제된 백업 또는 오브젝트 스토리지에 저장된 백업에서 NetApp Backup and Recovery를 사용하여 Oracle 데이터베이스 워크로드를 복원합니다.

.이 위치에서 복원
다양한 시작 위치에서 데이터베이스를 복원할 수 있습니다.

* 기본 위치(로컬 스냅샷)에서 복원
* 보조 저장소의 복제된 리소스에서 복원
* 개체 스토리지 백업에서 복원


.이 지점으로 복원
원래 위치로 데이터를 복원할 수 있지만, 이 비공개 미리보기 릴리스에서는 대체 위치로 복원하는 기능을 사용할 수 없습니다.

* 원래 위치로 복원




[[how-oracle-database-restore-works]]
== Oracle 데이터베이스 복원 작동 방식

Oracle 데이터베이스 워크로드를 복원할 때 다음과 같은 현상이 발생합니다.

* 로컬 스냅샷에서 데이터베이스를 복원하면 NetApp Backup and Recovery 백업의 데이터를 사용하여 _새로운_ 리소스를 만듭니다.
* 복제된 저장소에서 복원하면 원래 위치로 복원할 수 있습니다.
* 개체 스토리지에서 백업을 복원하면 데이터를 소스 스토리지나 온프레미스 ONTAP 시스템으로 복원하고 해당 위치에서 데이터베이스를 복구할 수 있습니다.


복원 페이지(검색 및 복원이라고도 함)에서는 정확한 이름, 데이터베이스가 있는 위치 또는 마지막으로 양호한 상태였던 날짜를 기억하지 못하더라도 데이터베이스를 복원할 수 있습니다.  필터를 사용하여 데이터베이스를 검색할 수 있습니다.



[[restore-an-oracle-database]]
== Oracle 데이터베이스 복원

필요에 따라 Oracle 데이터베이스를 특정 시점, 특정 시스템 변경 번호(SCN) 또는 마지막으로 정상 작동했던 상태로 복원할 수 있습니다. 스냅샷에서 데이터베이스를 복원하고 자동 복구 프로세스를 건너뛸 수도 있습니다. 예를 들어 수동으로 복구를 수행하려는 경우에 유용합니다. 데이터베이스는 이름 또는 특정 필터를 사용하여 검색할 수 있습니다.

*필수 NetApp Console 역할* 백업 및 복구 슈퍼 관리자 또는 백업 및 복구 복원 관리자 역할. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp Console 액세스 역할에 대해 알아보세요."^].

[NOTE]
====
PDB 또는 테이블스페이스를 특정 시점이나 SCN으로 복원하는 경우:

* PDB는 하나만 선택하십시오. 특정 시점 복구는 여러 개의 PDB를 복원하는 것과 호환되지 않습니다.
* `PDB$SEED`은(는) 특정 시점 복구를 위해 선택할 수 없습니다.
* 제어 파일 복원은 PDB 또는 PDB 테이블스페이스의 특정 시점 복구와 함께 사용할 수 없습니다.
* 데이터 백업과 필요한 로그 백업이 카탈로그에 등록되었는지 확인하십시오.
*  `SYSTEM`,  `SYSAUX`, 및  `UNDO` 테이블스페이스는 선택할 수 없습니다.
* 데이터 백업 및 필수 로그 백업이 카탈로그에 등록되었는지 확인하십시오.


====
.단계
. NetApp Console 메뉴에서 *보호 > 백업 및 복구*를 선택합니다.
. NetApp Backup and Recovery 메뉴에서 *복원*을 선택합니다.
. 이름 검색 필드 오른쪽에 있는 드롭다운 목록에서 *Oracle*을 선택합니다.
. 복원하려는 데이터베이스의 이름을 입력하거나 복원하려는 데이터베이스가 있는 데이터베이스 호스트를 필터링합니다.
+
검색 기준에 맞는 스냅샷 목록이 나타납니다.

. 복원하려는 데이터베이스에 대해 *복원* 버튼을 선택합니다.
. 복원 옵션을 선택하세요:
+
[role="tabbed-block"]
====
.특정 시점으로 복원
--
.. *특정 시점으로 복원*을 선택하세요.
.. *다음*을 선택하세요.
.. 드롭다운에서 날짜를 선택하고 *검색*을 선택하세요.
+
지정된 날짜 및 시간에 가장 가까운 스냅샷이 표시됩니다.

.. 선택적으로 *로그 백업 보기*를 선택하여 관련 로그 백업을 확인할 수 있습니다.
+
... 로그 백업이 마운트되었는지 확인하십시오.


.. 스냅샷이 여러 위치에 저장된 경우 사용할 소스 위치를 선택하고 위치 세부 정보를 추가하거나 검토하십시오.
.. *다음*을 선택하세요.


--
.특정 시스템 변경 번호(SCN)로 복원
--
.. *특정 시스템 변경 번호(SCN)로 복원*을 선택합니다.
.. *다음*을 선택하세요.
.. 복원 지점으로 사용할 SCN을 입력하고 *검색*을 선택합니다.
+
지정된 SCN에 대한 가장 최근의 스냅샷이 표시됩니다.

.. 선택적으로 *로그 백업 보기*를 선택하여 관련 로그 백업을 확인할 수 있습니다.
+
... 로그 백업이 마운트되었는지 확인하십시오.


.. 스냅샷이 여러 위치에 저장된 경우 사용할 소스 위치를 선택하고 위치 세부 정보를 추가하거나 검토하십시오.
.. *다음*을 선택하세요.


--
.최신 백업(마지막 정상 상태)으로 복원
--
.. *최신 백업으로 복원*을 선택하세요.
.. *다음*을 선택하세요.
+
최신 스냅샷이 표시됩니다. 복원 작업은 사용 가능한 모든 로그 백업을 사용하여 마지막으로 정상 작동했던 상태를 복구합니다.

.. 선택적으로 *로그 백업 보기*를 선택하여 관련 로그 백업을 확인할 수 있습니다.
+
... 로그 백업이 마운트되었는지 확인하십시오.


.. 스냅샷이 여러 위치에 저장된 경우 사용할 소스 위치를 선택하고 위치 세부 정보를 추가하거나 검토하십시오.
.. *다음*을 선택하세요.


--
.복구 없이 스냅샷에서 복원
--
.. *복구 없이 스냅샷에서 복원*을 선택합니다.
+
이 옵션을 선택하면 데이터베이스가 스냅샷에서 복원되지만 복구는 건너뜁니다(로그 백업은 적용되지 않음).

.. *다음*을 선택하세요.
+
사용 가능한 스냅샷이 표시됩니다.

.. 목록에서 스냅샷을 선택하고 *다음*을 선택합니다.
.. 스냅샷이 여러 위치에 저장된 경우 사용할 소스 위치를 선택하고 위치 세부 정보를 추가하거나 검토하십시오.
.. *다음*을 선택하세요.


--
====
. 복원 대상 및 설정을 선택하십시오.
+
[role="tabbed-block"]
====
.원래 위치로 복원
--
.. *대상 설정* 섹션에서 다음을 수행하십시오.
+
... RAC 데이터베이스의 경우 복원을 실행할 RAC 노드를 선택하십시오. 이 옵션은 RAC 데이터베이스에만 나타납니다.
... 복원할 항목을 선택하십시오:
+
**** 전체 데이터베이스 또는 컨테이너 데이터베이스(CDB)를 복원하려면 *모든 데이터 파일*을 선택하십시오.
**** 컨테이너의 다른 PDB에 영향을 주지 않고 CDB에서 하나 이상의 PDB를 복원하려면 *플러그형 데이터베이스(PDB)*를 선택합니다. 그런 다음 목록에서 PDB를 선택합니다.
**** 특정 PDB 테이블스페이스를 복원하려면 *플러그형 데이터베이스(PDB) 테이블스페이스*(CDB가 아닌 데이터베이스의 경우 *테이블스페이스*로 표시됨)를 선택합니다. 그런 다음 PDB와 테이블스페이스를 선택합니다.


... 선택적으로 *제어 파일* 옵션을 활성화하면 데이터베이스 제어 파일도 복원할 수 있습니다. 이 옵션은 PDB 또는 PDB 테이블스페이스의 특정 시점 복구 또는 SCN 복구에는 사용할 수 없습니다.
... 선택적으로, *복원 및 복구에 필요한 경우 데이터베이스 상태 변경* 옵션을 활성화하면 Backup and Recovery가 복구 유형에 따라 데이터베이스 상태를 관리할 수 있습니다.
... 선택적으로, 백업 후 새 데이터 파일이 추가되었거나 LVM 디스크 그룹에서 LUN이 추가, 삭제 또는 재생성된 경우 인플레이스 복원을 수행하려면 *Force in place restore* 옵션을 활성화하십시오. 이 옵션을 활성화하면 외부 파일 검사가 무시되고, 선택한 복원 옵션을 사용하여 데이터베이스 복구가 진행됩니다.
... PDB 또는 테이블스페이스를 특정 시점이나 SCN으로 복원할 때 아카이브 로그가 구성된 위치에 없는 경우 *외부 아카이브 로그 파일 위치* 필드에 외부 아카이브 로그 파일 위치를 지정하십시오.  `/`로 시작하는 파일 시스템 경로 또는  `+`로 시작하는 ASM 디스크 그룹을 입력하십시오. 텍스트 입력 필드 옆에 있는 "더하기" 및 "빼기" 버튼을 사용하여 위치를 추가하거나 제거하십시오. 이 필드는 복구 없이 스냅샷에서 복원하는 경우에는 나타나지 않습니다.
... 선택적으로 * 복구 후 데이터베이스 또는 컨테이너 데이터베이스를 읽기/쓰기 모드로 열기* 옵션을 활성화하고 복원 범위와 일치하는 하위 옵션을 선택하십시오(복구 없이 스냅샷에서 복원하는 경우에는 이러한 옵션이 나타나지 않습니다).
+
**** *모든 데이터 파일*: 복구 후 데이터베이스 또는 컨테이너 데이터베이스를 READ-WRITE 모드로 엽니다.
**** *PDB 또는 PDB 테이블스페이스*: 복구 후 플러그형 데이터베이스를 읽기/쓰기 모드로 엽니다.
**** *비CDB 테이블스페이스*: 복구 후 테이블스페이스를 온라인 상태로 전환하십시오.




.. *서문 및 후기* 섹션에서 다음을 수행하십시오.
+
... *사전 명령*: 선택적으로 이 옵션을 활성화하고 복원 작업 전에 실행해야 하는 스크립트의 전체 경로와 스크립트가 사용하는 인수를 입력하십시오.
... *추신*: 선택적으로 이 옵션을 활성화하고 복원 작업 이후에 실행되어야 하는 스크립트의 전체 경로와 스크립트가 취하는 인수를 입력합니다.
... 스크립트 실행 시간 제한 값을 선택합니다. 스크립트가 이 시간 내에 실행되지 않으면 복원 작업은 계속 진행됩니다.




--
.대체 위치로 복원
--
이번 미리 보기 릴리스에서는 Oracle 데이터베이스 워크로드에서 사용할 수 없습니다.

--
====
. *복원*을 선택하세요.

