---
sidebar: sidebar 
permalink: br-use-restore-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: NetApp Backup and Recovery 사용하면 보호 정책으로 보호한 애플리케이션을 복원할 수 있습니다. 
---
= 웹 UI를 사용하여 Kubernetes 애플리케이션을 복원합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 사용하면 보호 정책으로 보호한 애플리케이션을 복원할 수 있습니다. 애플리케이션을 복원하려면 애플리케이션에 최소 하나의 복원 지점이 있어야 합니다. 복원 지점은 로컬 스냅샷 또는 개체 저장소 백업(또는 둘 다)으로 구성됩니다. 로컬, 보조 또는 개체 저장소 아카이브를 사용하여 애플리케이션을 복원할 수 있습니다.

.시작하기 전에
Trident Protect를 사용하여 백업한 애플리케이션을 복원하는 경우 소스 클러스터와 타겟 클러스터 모두에 Trident Protect가 설치되어 있는지 확인하십시오.

.필수 NetApp Console 역할
조직 관리자 또는 SnapCenter 관리자. link:reference-roles.html["NetApp Backup and Recovery 액세스 역할에 대해 알아보세요"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp Console 액세스 역할에 대해 알아보세요."^] .

.단계
. NetApp Backup and Recovery 메뉴에서 *복원*을 선택합니다.
. 목록에서 Kubernetes 애플리케이션을 선택하고 해당 애플리케이션에 대해 *View and Restore*를 선택합니다.
+
복원 지점 목록이 나타납니다.

. 사용하려는 복원 지점의 *Restore* 버튼을 선택하십시오.


[discrete]
===== 일반 설정

. 복원할 소스 위치를 선택합니다.
. *클러스터* 목록에서 대상 클러스터를 선택합니다.
+

NOTE: 현재 Trident Protect에서 생성한 로컬 스냅샷을 다른 클러스터로 복원하는 것은 지원되지 않습니다.

. 원래 네임스페이스로 복원할지, 아니면 새 네임스페이스로 복원할지 선택하십시오.
. 새 네임스페이스로 복원하도록 선택한 경우 사용할 타겟 네임스페이스를 입력하십시오.
. *다음*을 선택하세요.


[discrete]
===== 리소스 선택

. 애플리케이션과 관련된 모든 리소스를 복원할지 아니면 필터를 사용하여 복원할 특정 리소스를 선택할지 선택하세요.


[role="tabbed-block"]
====
.모든 리소스 복원
--
. *모든 리소스 복원*을 선택합니다.
. *다음*을 선택하세요.


--
.특정 리소스 복원
--
. *선택적 리소스*를 선택하세요.
. 리소스 필터의 동작을 선택합니다.  *포함*을 선택하면 선택한 리소스가 복원됩니다.  *제외*를 선택하면 선택한 리소스가 복원되지 않습니다.
. 리소스 선택을 위한 필터를 정의하는 규칙을 추가하려면 *규칙 추가*를 선택합니다.  리소스를 필터링하려면 최소한 하나의 규칙이 필요합니다.
+
각 규칙은 리소스 네임스페이스, 레이블, 그룹, 버전, 종류 등의 기준으로 필터링할 수 있습니다.

. 각 규칙을 저장하려면 *저장*을 선택하세요.
. 필요한 규칙을 모두 추가한 후 *검색*을 선택하면 필터 기준과 일치하는 백업 아카이브에서 사용 가능한 리소스를 확인할 수 있습니다.
+

NOTE: 표시된 리소스는 현재 클러스터에 존재하는 리소스입니다.

. 결과에 만족하면 *다음*을 선택하세요.


--
====
[discrete]
===== 목적지 설정

. *대상 설정* 섹션을 확장하고 기본 스토리지 클래스, 다른 스토리지 클래스로 복원하거나 다른 클러스터로 복원하는 경우 스토리지 클래스를 타겟 클러스터에 매핑하도록 선택합니다.
. 다른 스토리지 클래스로 복원하도록 선택한 경우, 각 소스 스토리지 클래스와 일치하는 대상 스토리지 클래스를 선택하십시오.
. 선택적으로, Trident Protect를 사용하여 생성된 백업 또는 스냅샷을 복원하는 경우 복원 작업의 스토리지 버킷으로 사용된 AppVault의 세부 정보를 확인하십시오. 환경 또는 AppVault 상태가 변경된 경우 *App Vault 동기화*를 선택하여 세부 정보를 새로 고치십시오.
+

NOTE: Trident Protect를 사용하여 생성된 백업 또는 스냅샷을 복원하기 위해 Kubernetes 클러스터에 AppVault를 생성해야 하는 경우  https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-appvault-custom-resources.html["Trident Protect AppVault 객체를 사용하여 버킷을 관리하세요."]을 참조하십시오.

. 선택적으로 *복원 스크립트* 섹션을 확장하고 *Postscript* 옵션을 활성화하여 복원 작업 완료 후 실행될 실행 후크 템플릿을 선택할 수 있습니다. 필요한 경우 스크립트에 필요한 인수를 입력하고 리소스 레이블을 기준으로 리소스를 필터링하기 위한 레이블 선택기를 추가합니다.
. *복원*을 선택하세요.

