---
sidebar: sidebar 
permalink: br-use-hyperv-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 온프레미스 ONTAP 시스템에서 기본 및 보조 스토리지까지 Hyper-V 가상 머신을 보호하여 데이터가 보호되도록 할 수 있습니다. 
---
= Hyper-V 워크로드 보호 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 사용하여 Hyper-V VM을 보호하세요. NetApp Backup and Recovery 독립 실행형 인스턴스와 FCI 클러스터 인스턴스 모두에 대해 빠르고 공간 효율적이며, 크래시 일관성 및 VM 일관성을 보장하는 백업 및 복원 작업을 제공합니다. System Center Virtual Machine Manager(SCVMM)로 프로비저닝되어 CIFS 공유에 호스팅된 Hyper-V 가상 머신도 보호할 수 있습니다.

Hyper-V 워크로드를 Amazon Web Services S3 또는 StorageGRID 에 백업하고 Hyper-V 워크로드를 온프레미스 Hyper-V 호스트로 복원할 수 있습니다.

NetApp Backup and Recovery 사용하여 3-2-1 보호 전략을 구현합니다. 즉, 소스 데이터의 사본 3개를 2개의 서로 다른 스토리지 시스템에 두고, 나머지 사본 1개를 클라우드에 둡니다. 3-2-1 접근 방식의 이점은 다음과 같습니다.

* 여러 개의 데이터 사본을 보관하여 내부 및 외부 사이버 보안 위협으로부터 보호합니다.
* 여러 미디어 유형을 사용하면 하나의 미디어 유형에 물리적 또는 논리적 오류가 발생하는 경우에도 장애 조치를 실행할 수 있습니다.
* 온사이트 사본을 사용하면 데이터를 빠르게 복원할 수 있으며, 온사이트 사본이 손상된 경우 오프사이트 사본을 사용할 수 있습니다.


Hyper-V 호스트를 추가하고 리소스를 검색하면 NetApp Backup and Recovery 가 NetApp Hyper-V 플러그인과 NetApp SnapCenter Windows FileSystem 플러그인을 Hyper-V 호스트에 설치하여 가상 머신을 관리하고 보호하는 데 도움을 줍니다.


NOTE: NetApp Backup and Recovery UI 버전으로 전환하려면 다음을 참조하세요.link:br-start-switch-ui.html["이전 NetApp Backup and Recovery UI로 전환"] .

NetApp Backup and Recovery 사용하면 Hyper-V 워크로드와 관련된 다음 작업을 수행할 수 있습니다.

* link:br-start-discover-hyperv.html["Hyper-V 워크로드 검색"]
* link:br-use-hyperv-protection-groups.html["Hyper-V 워크로드에 대한 보호 그룹 생성 및 관리"]
* link:br-use-hyperv-backup.html["Hyper-V 워크로드 백업"]
* link:br-use-hyperv-restore.html["Hyper-V 워크로드 복원"]

