---
sidebar: sidebar 
permalink: br-use-manage-kubernetes-clusters.html 
keywords: discover, backup and recovery, snapcenter, kubernetes, k8s, clusters, applications, inventory 
summary: NetApp Backup and Recovery 사용하면 Kubernetes 클러스터를 검색하고 관리하여 클러스터에서 호스팅되는 리소스를 보호할 수 있습니다. 
---
= Kubernetes 클러스터 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 사용하면 Kubernetes 클러스터를 검색하고 관리하여 클러스터에서 호스팅되는 리소스를 보호할 수 있습니다.

.필수 NetApp Console 역할
조직 관리자 또는 SnapCenter 관리자. link:reference-roles.html["NetApp Backup and Recovery 액세스 역할에 대해 알아보세요"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp Console 액세스 역할에 대해 알아보세요."^] .


NOTE: Kubernetes 클러스터를 검색하려면 다음을 참조하세요.link:br-start-discover.html["Kubernetes 워크로드를 알아보세요"] .



== Kubernetes 클러스터 정보 편집

클러스터의 이름을 변경해야 하는 경우 클러스터를 편집할 수 있습니다.

.단계
. NetApp Backup and Recovery 에서 *인벤토리* > *클러스터*를 선택합니다.
. 클러스터 목록에서 편집하려는 클러스터를 선택하고 연관된 작업 메뉴를 선택합니다.
. *클러스터 편집*을 선택하세요.
. 클러스터 이름을 필요에 따라 변경하세요. 클러스터 이름은 검색 과정에서 Helm 명령에 사용한 이름과 일치해야 합니다.
. *완료*를 선택하세요.




== Kubernetes 클러스터 제거

Kubernetes 클러스터 보호를 중지하려면 보호를 비활성화하고 관련 애플리케이션을 삭제한 다음 NetApp Backup and Recovery 에서 클러스터를 제거합니다.  NetApp Backup and Recovery 클러스터나 해당 리소스를 삭제하지 않고 NetApp Console 인벤토리에서만 클러스터를 제거합니다.

.단계
. NetApp Backup and Recovery 에서 *인벤토리* > *클러스터*를 선택합니다.
. 클러스터 목록에서 편집하려는 클러스터를 선택하고 연관된 작업 메뉴를 선택합니다.
. *클러스터 제거*를 선택합니다.
. 확인 대화 상자에서 정보를 검토하고 *제거*를 선택하세요.

