---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp NetApp Backup and Recovery 사용하여 VMware 워크로드를 보호하세요. 
---
= NetApp Backup and Recovery 개요를 사용하여 VMware 워크로드 보호
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 사용하여 VMware VM과 데이터 저장소를 보호하세요.  NetApp Backup and Recovery 빠르고 공간 효율적이며, 충돌 대비 및 VM 대비 일관된 백업 및 복원 작업을 제공합니다. VMware 워크로드를 Amazon Web Services S3 또는 StorageGRID 에 백업하고 온프레미스 VMware 호스트로 VMware 워크로드를 복원할 수 있습니다.


NOTE: 이 버전의 NetApp Backup and Recovery VMware vCenter만 지원하며 vVols 이나 vVols 의 VM을 검색하지 않습니다.

NetApp Backup and Recovery 사용하여 3-2-1 전략을 구현합니다. 즉, 소스 데이터의 사본 3개를 2개의 서로 다른 스토리지 시스템에 두고, 나머지 사본 1개를 클라우드에 둡니다. 3-2-1 접근 방식의 이점은 다음과 같습니다.

* 여러 개의 데이터 사본을 보관하여 내부 및 외부 사이버 보안 위협으로부터 보호합니다.
* 다양한 유형의 미디어를 사용하면 한 유형의 미디어가 실패하더라도 복구하는 데 도움이 됩니다.
* 온사이트 사본에서 빠르게 복원할 수 있으며, 온사이트 사본이 손상된 경우 오프사이트 사본을 사용할 수 있습니다.



NOTE: NetApp Backup and Recovery UI 버전으로 전환하려면 다음을 참조하세요.link:br-start-switch-ui.html["이전 NetApp Backup and Recovery UI로 전환"] .

NetApp Backup and Recovery 사용하면 VMware 워크로드와 관련된 다음 작업을 수행할 수 있습니다.

* link:br-use-vmware-discovery.html["VMware 워크로드 알아보기"]
* link:br-use-vmware-protection-groups.html["VMware 워크로드에 대한 보호 그룹 생성 및 관리"]
* link:br-use-vmware-backup.html["VMware 워크로드 백업"]
* link:br-use-vmware-restore.html["VMware 워크로드 복원"]

