---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, on-premises, applications, virtual machines, backup and recovery 
summary: NetApp Backup and Recovery를 사용하여 온프레미스 ONTAP 시스템에서 Amazon Web Services, Microsoft Azure 또는 StorageGRID로 Microsoft SQL Server 애플리케이션 데이터를 보호하십시오. 
---
= NetApp Backup and Recovery를 사용하여 Microsoft SQL Server 워크로드를 보호합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
온프레미스 ONTAP 시스템의 Microsoft SQL Server 데이터베이스를 AWS, Azure 또는 StorageGRID로 백업하려면 NetApp Backup and Recovery를 사용하십시오. 기본 스토리지의 스냅샷, 2차 스토리지로의 복제, 오브젝트 스토리지로의 복사본을 포함하는 3-2-1 백업 전략을 구현하십시오.

NetApp Backup and Recovery NetApp SnapMirror 사용하여 스냅샷을 생성하고 이를 백업 위치로 전송함으로써 백업을 동기화합니다.

데이터를 보호하려면 다음 워크플로를 사용하십시오.

* link:concept-start-prereq-snapcenter-import.html["SnapCenter 에서 가져오는 경우 추가 항목 구성"]
* link:br-start-discover.html["Microsoft SQL Server 워크로드를 검색하고 선택적으로 SnapCenter 리소스를 가져옵니다."]
* link:br-use-mssql-backup.html["로컬 ONTAP 기본 스토리지의 로컬 스냅샷으로 워크로드 백업"]
* link:br-use-mssql-backup.html["ONTAP 보조 스토리지에 작업 부하 복제"]
* link:br-use-mssql-backup.html["개체 저장소 위치에 워크로드 백업"]
* link:br-use-mssql-backup.html["지금 워크로드를 백업하세요"]
* link:br-use-mssql-restore.html["작업 부하 복원"]
* link:br-use-mssql-clone.html["복제 워크로드"]
* link:br-use-manage-inventory.html["작업량 인벤토리 관리"]
* link:br-use-manage-snapshots.html["스냅샷 관리"]


작업 부하를 백업하려면 백업 및 복원 작업을 관리하는 정책을 만듭니다. 보다link:br-use-policies-create.html["정책 생성"] 자세한 내용은.

.지원되는 백업 대상
NetApp Backup and Recovery는 다음 소스 시스템에서 나열된 2차 시스템 및 공용/사설 클라우드의 오브젝트 저장소로 Microsoft SQL Server 인스턴스 및 데이터베이스 백업을 지원합니다. 스냅샷은 소스 시스템에 남아 있습니다.

[cols="33,33,33"]
|===
| 소스 시스템 | 2차 시스템(복제) | 대상 오브젝트 저장소(백업) 


| AWS의 Cloud Volumes ONTAP | AWS 온프레미스 ONTAP 시스템의 Cloud Volumes ONTAP | 아마존 S3 ONTAP S3 


| Azure의 Cloud Volumes ONTAP | Azure 온프레미스 ONTAP 시스템의 Cloud Volumes ONTAP | Azure Blob ONTAP S3 


| 온프레미스 ONTAP 시스템 | Cloud Volumes ONTAP 온프레미스 ONTAP 시스템 | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | 해당 없음 
|===
.지원되는 복원 대상
기본 스토리지, 2차 시스템(복제된 볼륨) 또는 오브젝트 스토리지(백업 파일)에 있는 백업에서 Microsoft SQL Server 인스턴스 및 데이터베이스를 다음 대상 시스템으로 복원할 수 있습니다. 스냅샷은 소스 시스템에 있으며 동일한 시스템으로만 복원할 수 있습니다.

[cols="33,33,33"]
|===
2+| 백업 파일 위치에서 | 대상 시스템으로 


| *오브젝트 저장소(백업)* | *2차 시스템(복제)* |  


| 아마존 S3 | AWS 온프레미스 ONTAP 시스템의 Cloud Volumes ONTAP | Cloud Volumes ONTAP AWS 온프레미스 ONTAP 시스템 ONTAP S3 


| Azure Blob | Azure 온프레미스 ONTAP 시스템의 Cloud Volumes ONTAP | Azure 온프레미스 ONTAP 시스템 ONTAP S3의 ​​Cloud Volumes ONTAP 


| StorageGRID | Cloud Volumes ONTAP 온프레미스 ONTAP 시스템 | 온프레미스 ONTAP 시스템 ONTAP S3 
|===

NOTE: "사내 ONTAP 시스템"에 대한 참조에는 FAS 및 AFF 시스템이 포함됩니다.
