---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: 운영 환경, 콘솔 에이전트, 콘솔 계정의 준비 상태를 확인하여 NetApp Backup and Recovery 시작하세요.  NetApp Backup and Recovery 사용하려면 다음과 같은 필수 구성 요소가 필요합니다. 
---
= NetApp Backup and Recovery 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery를 사용하기 전에 NetApp Console과 운영 환경이 다음 요구 사항을 충족하는지 확인하십시오.



== NetApp Console 준비

NetApp Backup and Recovery는 NetApp Console을 통해 액세스할 수 있습니다. Backup and Recovery를 위해 Console을 준비하려면 다음을 수행해야 합니다.

* Console 에이전트 추가
* 스토리지 시스템을 하나 이상 추가합니다
* Console 조직 및 사용자 역할 구성


이 준비를 완료하려면 NetApp Console에서 Organization admin 또는 Super admin 역할이 필요합니다.

NetApp Console에 대한 자세한 내용은 https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["통합 스토리지 관리를 위한 NetApp Console"^]을 참조하십시오.



=== 초기 NetApp Console 설정 완료

아직 완료하지 않았다면 NetApp Console의 초기 설정을 완료하십시오.

https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["NetApp Console(SaaS 애플리케이션) 시작 워크플로"^]



=== Console 에이전트 배포

콘솔 에이전트는 스토리지 인프라를 NetApp Console에 연결하기 위해 네트워크에 설치하는 경량 소프트웨어 구성 요소입니다. 이를 통해 고급 스토리지 오케스트레이션, 데이터 서비스 및 안전한 클라우드 통합이 가능합니다.

https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["콘솔 에이전트에 대해 알아보세요"^] https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html["Console 에이전트 배포"^]



=== 스토리지 시스템 추가

Backup and Recovery에서 워크로드를 보호하려면 먼저 Console에 ONTAP 스토리지 시스템을 추가해야 합니다.

https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["NetApp Console에서 온프레미스 ONTAP 클러스터 검색"^]



=== 조직 및 사용자 역할 구성

조직, 프로젝트 및 사용자 역할에 대해 알아본 다음 사용자가 작업을 수행하는 데 필요한 적절한 권한을 구성하십시오.

리소스 액세스 제어를 위해 조직 및 프로젝트를 사용하는 방법에 대한 자세한 내용은 https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html["NetApp Console 조직에 사용자 추가"]을 참조하십시오.

 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Console 의 NetApp Backup and Recovery 역할"]NetApp Backup and Recovery에서 작업을 수행하는 데 필요한 역할 및 권한에 대한 자세한 내용은 해당 문서를 참조하십시오.



== 오브젝트 스토리지에 대한 백업 요구사항

객체 스토리지를 백업 대상으로 사용하려면 AWS S3, Google Cloud Storage, Microsoft Azure Blob, StorageGRID 또는 ONTAP 계정과 적절한 액세스 권한이 구성되어 있어야 합니다.



== ONTAP 볼륨 워크로드 보호를 위한 요구 사항

NetApp Backup and Recovery for ONTAP 볼륨 워크로드를 사용하려면 다음과 같은 호스트 시스템, 공간 및 크기 조정 요구 사항을 충족해야 합니다.

* ONTAP 9.8 이상이 필요합니다.
* FlexGroup 볼륨 보호에는 ONTAP 9.12.1 이상이 필요합니다. 자세한 내용은 link:br-reference-limitations.html["ONTAP 볼륨에 대한 NetApp Backup and Recovery 의 알려진 제한 사항"]을 참조하십시오.
* S3 호환 객체 스토리지에 백업하거나 복원하려면 ONTAP 9.17.1 이상이 필요합니다.
* 온프레미스 ONTAP 인스턴스에 ONTAP One 라이센스가 활성화되어 있어야 합니다.


지원되는 기능, 볼륨 유형, 백업 및 복원 대상 등에 대한 자세한 내용은 link:prev-ontap-protect-overview.html["ONTAP 볼륨 데이터 보호"]을(를) 참조하십시오.



== Microsoft SQL Server 워크로드 보호를 위한 요구 사항

Microsoft SQL Server 워크로드에 NetApp Backup and Recovery 사용하려면 다음과 같은 호스트 시스템, 공간 및 크기 조정 전제 조건이 필요합니다.

[cols="33,66a"]
|===
| 목 | 요구 사항 


| 운영 체제  a| 
Microsoft Windows 지원되는 버전에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp 상호 운용성 매트릭스 도구"^] .



| Microsoft SQL Server 버전  a| 
2012 이상 버전은 VMware Virtual Machine File System(VMFS) 및 VMware Virtual Machine Disk(VMDK) NFS를 지원합니다.



| SnapCenter 서버 버전  a| 
SnapCenter 에서 NetApp Backup and Recovery 로 기존 데이터를 가져오려면 SnapCenter Server 버전 5.0 이상이 필요합니다.


NOTE: 이미 SnapCenter 가 있는 경우 SnapCenter 에서 가져오기 전에 필수 구성 요소를 충족했는지 먼저 확인하세요.  보다link:concept-start-prereq-snapcenter-import.html["SnapCenter 에서 리소스를 가져오기 위한 전제 조건"] .



| SQL Server 호스트의 플러그인에 대한 최소 RAM  a| 
1GB



| SQL Server 호스트의 플러그인에 대한 최소 설치 및 로그 공간  a| 
5GB

충분한 디스크 공간을 할당하고 로그 폴더의 저장 공간 소비량을 모니터링합니다.  필요한 로그 공간은 수행된 백업 횟수와 데이터 보호 작업 빈도에 따라 달라집니다.  충분한 공간이 없으면 작업에 대한 로그가 생성되지 않습니다.



| 필수 소프트웨어 패키지  a| 
* ASP.NET Core Runtime 8.0.24 Hosting Bundle(및 이후의 모든 8.0.x 패치)
* PowerShell 7.4.13


지원되는 버전에 대한 최신 정보는 다음을 참조하세요. https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["NetApp 상호 운용성 매트릭스 도구"^] .

|===
[cols="33,66a"]
|===
| 데이터베이스 호스트 | 지원되는 스토리지 


| 물리적 서버  a| 
* Fibre Channel을 통해 제공되는 LUN
* iSCSI를 통해 제공되는 LUN




| VMware VM  a| 
* iSCSI 이니시에이터에 의해 게스트 시스템에 직접 연결된 iSCSI LUN
* 가상 머신 파일 시스템(VMFS)
* NFS 데이터 저장소




| Hyper-V VM  a| 
iSCSI 이니시에이터에 의해 게스트 시스템에 직접 연결된 iSCSI LUN


NOTE: NetApp 스토리지에 프로비저닝된 패스스루 디스크 또는 VHD/VHDX 파일에 저장된 데이터베이스 보호는 지원되지 않습니다.

|===


== VMware 워크로드 보호를 위한 요구 사항

VMware 워크로드를 검색하고 보호하려면 특정 요구 사항이 필요합니다.

|===
| 요구 사항 | 지원됨 


| 데이터 저장소 유형 | NFSv3, NFSv4.1 및 VMFS 


| VMware ESXi Server 버전 | 7.0U1 이상 


| VMware vCenter vSphere 버전 | 7.0U1 이상 


| VMware Tools | 파일 및 폴더 복원 기능과 VM 일관성 백업을 사용하려면 VMware Tools가 필요합니다. VMware Tools 버전이 ESXi Server 버전과 일치하는지 확인하려면 https://packages.vmware.com/tools/versions["VMware 버전 매핑 정보"]을 참조하십시오. 


| IP 주소 유형 | IPv4, IPv6 


| VMware TLS 버전 | 1.2, 1.3 


| 연결된 스토리지  a| 
* ONTAP 9.13.1 이상
* 버전 9.13.1 이상을 실행하는 Amazon FSx for NetApp ONTAP 스토리지 시스템
* ASA r2 SAN 전용 시스템(ONTAP 9.17.1 이상 필요)


|===
[cols="33,66a"]
|===
| 포트 유형 | 사전 구성된 포트 


| VMware ESXi 서버 포트  a| 
443(HTTPS), 양방향. 파일 및 폴더 복원 기능은 이 포트를 사용합니다.



| 스토리지 클러스터 또는 스토리지 VM 포트  a| 
* 443(HTTPS), 양방향.
* 80(HTTP), 양방향. 이 포트는 가상 어플라이언스와 스토리지 VM 또는 스토리지 VM이 포함된 클러스터 간의 통신에 사용됩니다.


|===
.VMware 워크로드 보호를 위한 역할 기반 액세스 제어(RBAC) 요구 사항
VMware 워크로드를 사용하려면 NetApp Console 사용자 계정에 NetApp Backup and Recovery 최고 관리자 역할이 있어야 합니다.

Backup and Recovery 역할에 대한 자세한 내용은 https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["NetApp Console의 Backup and Recovery 역할"]를 참조하십시오.



== KVM 워크로드 보호를 위한 요구 사항

KVM 가상 머신을 검색하고 보호하려면 특정 요구 사항이 필요합니다.

* 커널 버전 5.14.0-503.22.1.el9_5.x86_64(장기) 이상을 실행하는 최신 Linux 배포판
* KVM 호스트와 가상 머신은 관리 플랫폼을 통해 관리되어야 합니다. NetApp Backup and Recovery 다음과 같은 관리 플랫폼을 지원합니다.
+
** Apache CloudStack 4.22.0.0


* 콘솔 에이전트에서 KVM 호스트로 향하는 22번 포트로의 인바운드 네트워크 트래픽이 허용되어 있는지 확인하십시오.
* QEMU 게스트 에이전트 버전 9.0.0 이상
* libvirt 버전 10.5.0 이상



NOTE: KVM 워크로드 복원이 성공적으로 완료되도록 하려면 KVM 백업에 사용하는 보호 정책에서 *VM 일관성 스냅샷 사용* 설정이 활성화되어 있는지 확인하십시오.

[NOTE]
====
루트가 아닌 사용자가 관리하는 KVM VM의 보호를 활성화하려면 다음 단계를 따르세요.

. NFS3 유형으로 볼륨을 마운트하여 다음을 사용하지 않도록 합니다. `nobody` 사용자 및 그룹.
. 다음 명령을 사용하여 루트가 아닌 사용자를 추가하세요. `qemu` 기존 그룹을 보존하면서 그룹화:
+
[source, console]
----
usermod -aG qemu <non-root-user>
----
. 다음 명령을 사용하여 마운트 경로의 소유권을 부여합니다. `qemu` 사용자 및 그룹과 마운트 경로에 대한 권한 변경:
+
[source, console]
----
chown -R qemu:qemu <kvm_vm_mount_path> & chmod 771 <kvm_vm_mount_path>
----
. 기존 NetApp_SnapCenter_Backups 디렉토리가 있으면 삭제합니다.


====


== Oracle Database 워크로드 보호를 위한 요구 사항

환경이 Oracle Database 리소스를 검색하고 보호하기 위한 특정 요구 사항을 충족하는지 확인하십시오.

|===
| 요구 사항 | 지원됨 


| 배포 토폴로지  a| 
* 독립 실행형(NFS, SAN, ASM SAN)
* ASM 기반 RAC(VMFS의 VMDK)




| Oracle Database 버전  a| 
* Oracle Database 19c
* Oracle Database 21c
* Oracle AI Database 26ai




| 데이터베이스 스토리지 | NetApp ONTAP(기본 또는 보조)에 배포해야 합니다. 


| 호스트 OS  a| 
* Red Hat Enterprise Linux 8
* Red Hat Enterprise Linux 9




| 오브젝트 스토리지(백업 타겟)  a| 
* Azure 개체 스토리지
* 아마존 AWS
* NetApp StorageGRID
* ONTAP S3


|===


== Kubernetes 애플리케이션 보호를 위한 요구 사항

Kubernetes 리소스를 검색하고 Kubernetes 애플리케이션을 보호하려면 특정 요구 사항이 필요합니다.

NetApp Console 요구 사항은 <<NetApp Console 준비>>을 참조하십시오.


NOTE: NetApp에서는 에이전트 IP 주소가 변경될 경우 발생할 수 있는 문제를 방지하기 위해 Kubernetes 워크로드에 사용하는 Console 에이전트에 고정 IP 주소를 할당할 것을 강력히 권장합니다.

* 기본 ONTAP 시스템(ASA r2 시스템은 지원되지 않음)
* NetApp Trident 25.02 이상 버전
* NetApp Trident Protect 26.05 이상(검색 중에 Kubernetes 클러스터에 설치됨)
* Kubernetes 클러스터 - 지원되는 Kubernetes 배포판 및 버전에는 https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["Trident Protect"]에서 지원하는 것들이 포함됩니다.
+
** Kubernetes 클러스터, Trident Protect 커넥터 및 Trident Protect 프록시 간의 아웃바운드 방향에서 TCP 포트 443이 필터링되지 않았는지 확인하십시오.






== Hyper-V 워크로드 보호를 위한 요구 사항

Hyper-V 인스턴스가 가상 머신을 검색하고 보호하기 위한 특정 요구 사항을 충족하는지 확인하세요.

|===
| 요구 사항 | 지원됨 


| Microsoft Hyper-V | 2019, 2022 및 2025 에디션 


| ASP.NET Core 런타임 | 8.0.24 Hosting Bundle(및 이후의 모든 8.0.x 패치) 


| PowerShell | 7.4.13 이상 


| 관리자가 아닌 사용자가 Hyper-V VM을 보호하는 경우 해당 사용자에게 다음 권한이 있는지 확인하십시오  a| 
* 로컬 관리자 그룹의 구성원
* "서비스로 로그온" 로컬 보안 정책의 일부




| Windows 방화벽 설정에서 다음 포트에 대해 양방향 HTTPS 트래픽이 허용되는지 확인하십시오  a| 
* TCP 8144(NetApp Plugin for Hyper-V)
* TCP 8145 (NetApp Plugin for Windows)




| 연결된 스토리지  a| 
* ONTAP 9.13.1 이상
* SMB 공유
* iSCSI 또는 파이버 채널을 통해 연결된 SAN 스토리지


|===
.Hyper-V 호스트의 하드웨어 요구 사항
* 독립형 및 FCI 클러스터 호스트가 지원됩니다.
* Hyper-V 호스트의 NetApp Hyper-V 플러그인에 최소 1GB RAM 필요
* Hyper-V 호스트의 플러그인을 위한 최소 5GB 설치 및 로그 공간
+

NOTE: Hyper-V 호스트에 로그 폴더에 충분한 디스크 공간을 할당하고 사용량을 정기적으로 모니터링하세요.  필요한 공간은 백업 및 데이터 보호 작업이 얼마나 자주 발생하는지에 따라 달라집니다.  공간이 충분하지 않으면 로그가 생성되지 않습니다.



.NetApp ONTAP 구성 요구 사항
* 기본 ONTAP 시스템(ONTAP 9.14.1 이상)
* SMB 공유를 사용하여 가상 머신 데이터를 저장하는 Hyper-V 배포의 경우 ONTAP 시스템에서 지속적인 가용성 공유 속성이 활성화되어 있는지 확인하십시오. 지침은  https://docs.netapp.com/us-en/ontap/smb-hyper-v-sql/configure-shares-continuous-availability-task.html["ONTAP 문서"^]을 참조하십시오.

