---
sidebar: sidebar 
permalink: enable-preview-features.html 
keywords: preview features, preview, Backup and Recovery, configuration, NetApp Backup and Recovery 
summary: NetApp Backup and Recovery의 미리 보기 및 숨겨진 기능을 활성화합니다. 
---
= NetApp Backup and Recovery의 미리 보기 및 숨겨진 기능을 활성화합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery의 미리 보기 및 숨겨진 기능을 활성화합니다.

*필수 NetApp Console 역할* 백업 및 복구 슈퍼 관리자.  에 대해 알아보세요link:reference-roles.html["백업 및 복구 역할과 권한"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["모든 서비스에 대한 NetApp Console 액세스 역할에 대해 알아보세요."^] .



== 사용 가능한 미리 보기 기능

NetApp Backup and Recovery에 대해 다음과 같은 미리 보기 기능을 활성화할 수 있습니다.

[cols="50,50"]
|===
| 기능 플래그 | 기능 설명 


| `"folder-restore-from-local": true` | 로컬 ONTAP 볼륨 스냅샷에서 폴더 수준 복원을 활성화합니다. 기본적으로 ONTAP은 객체 스토리지 백업에서 폴더 복원만 지원합니다. 이 플래그를 활성화하면 로컬 및 복제된 스냅샷에서 전체 디렉터리도 복원할 수 있습니다. 


| `"prioritize-restore": true` | NetApp Backup and Recovery 웹 UI의 복원 워크플로에서 *기존 작업 대기열보다 복원 우선순위 지정* 옵션을 선택할 수 있도록 합니다. 복원 워크플로에서 이 옵션을 선택하면 복원 작업이 대기열에 있는 다른 작업보다 우선순위가 높아져 대기열이 바쁜 경우에도 실행됩니다. 
|===


== 미리보기 기능 활성화

아직 정식 출시되지 않은 기능을 사용하려면 미리 보기 기능 플래그 옵션을 활성화하십시오. 프로덕션 환경에서는 미리 보기 기능을 사용할 때 주의해야 합니다.

.단계
. SSH를 사용하여 Console 에이전트에 로그인하십시오.
. 루트 사용자로 변경:
+
[source, console]
----
sudo su
----
. Docker에서 Backup and Recovery 볼륨을 찾으세요.
+
[source, console]
----
docker volume ls | grep cbs
----
+
출력은 다음과 유사해야 합니다.

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
. 볼륨의 마운트 지점을 찾으십시오.
+
[source, console]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
클라우드 배포와 프라이빗 배포 간에 마운트 지점이 다릅니다. 다음 출력 예시는 클라우드 배포를 보여줍니다.

+
[listing]
----
/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. 마운트 지점 디렉토리 안에 있는 docker 볼륨 구성 디렉토리로 이동합니다. 예를 들면 다음과 같습니다.
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data/cbs_config
----
. 활성화하려는 각 기능 플래그에 대한 키/값 쌍과 다음 JSON 구조를 포함하는 파일을 생성합니다. 배포 유형에 따라 파일 이름을 지정합니다.
+
** 클라우드 배포: `production-customer.json`
** 프라이빗/다크 사이트 배포: `darksite-customer.json`
+
기능 플래그 정보는 <<anchor-flags,사용 가능한 플래그>>을(를) 참조하십시오. 예:

+
[source, json]
----
{
  "feature-flags": {
    "folder-restore-from-local": true,
    "prioritize-restore": true
  }
}
----


. Backup and Recovery 컨테이너를 다시 시작합니다.
+
[source, console]
----
docker restart cloudmanager_cbs
----
. 웹 브라우저에서 Backup and Recovery UI를 새로 고침하세요.
+

NOTE: 미리 보기 기능을 비활성화하려면 동일한 단계를 따르되 기능 플래그 값을 `false`로 설정하십시오.





== 스토리지 VM에 속한 모든 볼륨에 대한 인덱싱을 비활성화합니다

각 개별 볼륨에 대해 인덱싱을 비활성화하는 대신 특정 스토리지 VM에 속한 모든 볼륨에 대해 인덱싱을 비활성화하려면 다음 단계를 수행하십시오.

.단계
. SSH를 사용하여 Console 에이전트에 로그인하십시오.
. 루트 사용자로 변경:
+
[source, console]
----
sudo su
----
. Docker에서 Backup and Recovery 볼륨을 찾으세요.
+
[source, console]
----
docker volume ls | grep cbs
----
+
출력은 다음과 유사해야 합니다.

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
. 볼륨의 마운트 지점을 찾으십시오.
+
[source, console]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
클라우드 배포와 프라이빗 배포 간에 마운트 지점이 다릅니다. 다음 출력 예시는 클라우드 배포를 보여줍니다.

+
[listing]
----
/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. 마운트 지점 디렉토리 안에 있는 docker 볼륨 구성 디렉토리로 이동합니다. 예를 들면 다음과 같습니다.
+
[source, console]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data/cbs_catalog_config
----
.  `production-customer.json`이라는 파일을 다음 내용으로 생성합니다. 예제의 스토리지 VM 이름을 사용자 환경의 스토리지 VM 이름으로 바꿉니다.
+
[source, json]
----
{
  "indexing": {
    "svms-not-to-index": "storage_vm_1,storage_vm_2,storage_vm_3"
  }
}
----
. Backup and Recovery 인덱싱 카탈로그 컨테이너를 다시 시작합니다.
+
[source, console]
----
docker restart cloudmanager_cbs_catalog
----

