---
sidebar: sidebar 
permalink: prev-vmware-policy-create.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp NetApp Backup and Recovery 사용하여 VMware 워크로드를 보호하세요. 
---
= NetApp Backup and Recovery 에서 데이터 저장소를 백업하는 정책 만들기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery 에서 제공되는 다음 사전 정의된 정책 중 하나를 사용하거나 정책을 만들 수 있습니다.


NOTE: NetApp Backup and Recovery 워크로드로 전환하려면 다음을 참조하세요.link:br-start-switch-ui.html["다양한 NetApp Backup and Recovery 워크로드로 전환"] .

.시작하기 전에
* 미리 정의된 정책을 편집하지 않으려면 정책을 만들어야 합니다.
* 백업을 개체 저장소에서 보관 저장소로 옮기려면 ONTAP 9.10.1 이상을 실행해야 하며 Amazon Web Services 또는 Microsoft Azure가 클라우드 공급자여야 합니다.
* 각 클라우드 공급자에 대해 아카이브 액세스 계층을 구성해야 합니다.


.이 작업에 관하여
NetApp Console 에서 사용할 수 있는 미리 정의된 정책은 다음과 같습니다.

|===
| 정책 이름 | 상표 | 유지 가치 


 a| 
1년 일일 LTR(장기 유지율)
 a| 
일일
 a| 
366



 a| 
5년 일일 LTR
 a| 
일일
 a| 
1830



 a| 
7년 주간 LTR
 a| 
주간
 a| 
370



 a| 
10년 월 LTR
 a| 
월간 간행물
 a| 
120

|===
.단계
. 가상 머신 페이지의 설정 드롭다운 목록에서 *정책*을 선택합니다.
. *정책 만들기*를 선택하세요.
. 정책 세부 정보 섹션에서 정책 이름을 지정합니다.
. 보존 섹션에서 보존 유형 중 하나를 선택하고 보존할 백업 수를 지정합니다.
. 백업 저장소 소스로 기본 저장소 또는 보조 저장소를 선택합니다.
. (선택 사항) 비용 최적화를 위해 일정 기간이 지난 후 개체 저장소에서 보관 저장소로 백업을 이동하려면 *계층 백업을 보관 저장소로* 확인란을 선택하고 백업을 보관해야 하는 일수를 입력합니다.
. *만들기*를 선택하세요.
+

NOTE: 데이터 저장소와 연결된 정책은 편집하거나 삭제할 수 없습니다.


