---
sidebar: sidebar 
permalink: prev-vmware-register-snapcenter.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: NetApp NetApp Backup and Recovery를 사용하여 VMware 워크로드를 보호하세요. 
---
= NetApp 백업 및 복구와 함께 사용할 SnapCenter Plug-in for VMware vSphere 등록
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
데이터 저장소와 가상 머신이 표시되도록 하려면 NetApp Backup and Recovery에서 SnapCenter Plug-in for VMware vSphere 등록해야 합니다.  관리자 액세스 권한이 있는 사용자만 SnapCenter Plug-in for VMware vSphere 등록할 수 있습니다.

[]
====
*참고* NetApp 백업 및 복구 워크로드로 전환하려면 다음을 참조하세요.link:br-start-switch-ui.html["다양한 NetApp 백업 및 복구 워크로드로 전환"] .

====
.단계
. NetApp 콘솔 UI에서 *보호* > *백업 및 복구* > *가상 머신*을 선택합니다.
. *설정* 드롭다운에서 * SnapCenter Plug-in for VMware vSphere*을 선택합니다.
. * SnapCenter Plug-in for VMware vSphere 등록*을 선택합니다.
. 다음 세부 사항을 지정하세요.
+
.. SnapCenter Plug-in for VMware vSphere 에서 SnapCenter Plug-in for VMware vSphere 의 FQDN 또는 IP 주소를 지정합니다.
.. 포트 필드에서 SnapCenter Plug-in for VMware vSphere 실행되는 포트 번호를 지정합니다.
+
기본 8144 포트에서 실행되는 온프레미스 SnapCenter Plug-in for VMware vSphere 호스트와 Amazon Web Services, Microsoft Azure, Google Cloud Platform 등의 클라우드 공급자 또는 온프레미스에서 실행되는 콘솔 에이전트 인스턴스 간의 통신이 열려 있는지 확인해야 합니다.

.. 사용자 이름 및 비밀번호 필드에서 관리자 역할을 가진 vCenter 사용자의 자격 증명을 지정합니다.


. *등록*을 선택하세요.


*끝난 후*

등록된 SnapCenter Plug-in for VMware vSphere 사용하여 보호되는 모든 데이터 저장소와 가상 머신을 보려면 *백업 및 복구* > *가상 머신*을 선택합니다.
