---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database, dark site, private mode, restore database, backup and recovery, Console agent 
summary: '인터넷 접속이 불가능한 사이트("개인 모드"라고 함)에서 NetApp Backup and Recovery를 사용하는 경우, NetApp Backup and Recovery 구성 데이터는 백업이 저장되는 StorageGRID 또는 ONTAP S3 버킷에 백업됩니다.  나중에 콘솔 에이전트 호스트 시스템에 문제가 발생하면 새로운 콘솔 에이전트를 배포하고 중요한 NetApp 백업 및 복구 데이터를 복원할 수 있습니다.' 
---
= 다크 사이트에서 NetApp 백업 및 복구 구성 데이터 복원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
인터넷 접속이 불가능한 사이트(개인 모드)에서 NetApp Backup and Recovery를 사용하는 경우, NetApp Backup and Recovery 구성 데이터는 백업이 저장되는 StorageGRID 또는 ONTAP S3 버킷에 백업됩니다.  콘솔 에이전트 호스트 시스템에 문제가 있는 경우 새로운 콘솔 에이전트를 배포하고 중요한 NetApp 백업 및 복구 데이터를 복원할 수 있습니다.


NOTE: 이 절차는 ONTAP 볼륨 데이터에만 적용됩니다.

콘솔 에이전트가 클라우드 공급자 또는 인터넷 액세스가 가능한 자체 호스트 시스템에 배포된 SaaS 환경에서 NetApp Backup and Recovery를 사용하는 경우 모든 중요한 NetApp Backup and Recovery 구성 데이터가 클라우드에 백업되고 보호됩니다.  콘솔 에이전트에 문제가 있는 경우 새 콘솔 에이전트를 만들고 시스템을 추가하면 백업 세부 정보가 자동으로 복원됩니다.

백업되는 데이터에는 두 가지 유형이 있습니다.

* NetApp 백업 및 복구 데이터베이스 - 모든 볼륨, 백업 파일, 백업 정책 및 구성 정보 목록이 포함되어 있습니다.
* 색인된 카탈로그 파일 - 볼륨 데이터를 복원할 때 검색을 매우 빠르고 효율적으로 수행할 수 있는 검색 및 복원 기능에 사용되는 자세한 색인이 포함되어 있습니다.


이 데이터는 하루에 한 번 자정에 백업되며, 각 파일의 최대 7개 사본이 보관됩니다. 콘솔 에이전트가 여러 개의 온프레미스 ONTAP 시스템을 관리하는 경우 NetApp 백업 및 복구 파일은 먼저 활성화된 시스템의 버킷에 위치하게 됩니다.


TIP: NetApp 백업 및 복구 데이터베이스나 인덱싱된 카탈로그 파일에는 볼륨 데이터가 포함되지 않습니다.



== NetApp 백업 및 복구 데이터를 새 콘솔 에이전트로 복원

온프레미스 콘솔 에이전트에 심각한 오류가 발생한 경우 새 콘솔 에이전트를 설치한 다음 NetApp 백업 및 복구 데이터를 새 콘솔 에이전트로 복원해야 합니다.

NetApp 백업 및 복구 시스템을 작동 상태로 되돌리려면 다음 작업을 수행해야 합니다.

* 새 콘솔 에이전트 설치
* NetApp 백업 및 복구 데이터베이스 복원
* 인덱싱된 카탈로그 파일 복원
* 온프레미스 ONTAP 시스템과 StorageGRID 시스템을 모두 NetApp 콘솔 UI로 다시 검색하세요.


시스템이 다시 정상적으로 작동하는지 확인한 후에는 새로운 백업 파일을 만드는 것이 좋습니다.

.필요한 것
백업 파일이 저장되어 있는 StorageGRID 또는 ONTAP S3 버킷에서 최신 데이터베이스 및 인덱스 백업에 액세스해야 합니다.

* NetApp 백업 및 복구 MySQL 데이터베이스 파일
+
이 파일은 버킷의 다음 위치에 있습니다. `netapp-backup-<GUID>/mysql_backup/` , 그리고 그것은 이름이 붙습니다 `CBS_DB_Backup_<day>_<month>_<year>.sql` .

* 색인된 카탈로그 백업 zip 파일
+
이 파일은 버킷의 다음 위치에 있습니다. `netapp-backup-<GUID>/catalog_backup/` , 그리고 그것은 이름이 붙습니다 `Indexed_Catalog_DB_Backup_<db_name>_<day>_<month>_<year>.zip` .





=== 새로운 온프레미스 Linux 호스트에 새 콘솔 에이전트 설치

새로운 콘솔 에이전트를 설치할 때는 원래 콘솔 에이전트에 설치했던 것과 동일한 소프트웨어 릴리스를 다운로드해야 합니다.  NetApp 백업 및 복구 데이터베이스 구조가 주기적으로 변경되면 최신 소프트웨어 릴리스가 원래 데이터베이스 백업과 호환되지 않을 수 있습니다. 당신은 할 수 있습니다 https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-connector.html["백업 데이터베이스를 복원한 후 콘솔 에이전트 소프트웨어를 최신 버전으로 업그레이드합니다."^] .

. https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html["새로운 온프레미스 Linux 호스트에 콘솔 에이전트 설치"^]
. 방금 만든 관리자 사용자 자격 증명을 사용하여 콘솔에 로그인합니다.




=== NetApp 백업 및 복구 데이터베이스 복원

. 백업 위치에서 MySQL 백업을 새 콘솔 에이전트 호스트로 복사합니다. 아래에서는 "CBS_DB_Backup_23_05_2023.sql"이라는 예제 파일 이름을 사용하겠습니다.
. Docker 또는 Podman 컨테이너를 사용하는지에 따라 다음 명령 중 하나를 사용하여 백업을 MySQL Docker 컨테이너에 복사합니다.
+
[source, cli]
----
docker cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
+
[source, cli]
----
podman cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
. Docker 또는 Podman 컨테이너를 사용하는지에 따라 다음 명령 중 하나를 사용하여 MySQL 컨테이너 셸을 입력합니다.
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
+
[source, cli]
----
podman exec -it ds_mysql_1 sh
----
. 컨테이너 셸에서 "env"를 배포합니다.
. MySQL DB 비밀번호가 필요하므로 "MYSQL_ROOT_PASSWORD" 키 값을 복사합니다.
. 다음 명령을 사용하여 NetApp Backup and Recovery MySQL DB를 복원합니다.
+
[source, cli]
----
mysql -u root -p cloud_backup < CBS_DB_Backup_23_05_2023.sql
----
. 다음 SQL 명령을 사용하여 NetApp Backup and Recovery MySQL DB가 올바르게 복원되었는지 확인하세요.
+
[source, cli]
----
mysql -u root -p cloud_backup
----
+
비밀번호를 입력하세요.

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
표시된 볼륨이 원래 환경에 있던 볼륨과 동일한지 확인하세요.





=== 인덱싱된 카탈로그 파일 복원

. 백업 위치에서 Indexed Catalog 백업 zip 파일(예시 파일 이름 "Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip"을 사용함)을 "/opt/application/netapp/cbs" 폴더에 있는 새 콘솔 에이전트 호스트로 복사합니다.
. 다음 명령을 사용하여 "Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip" 파일의 압축을 풉니다.
+
[source, cli]
----
unzip Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip -d catalogdb1
----
. *ls* 명령을 실행하여 "catalogdb1" 폴더가 생성되었고 그 아래에 "changes"와 "snapshots"라는 하위 폴더가 있는지 확인합니다.




=== ONTAP 클러스터와 StorageGRID 시스템을 알아보세요

. https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["온프레미스 ONTAP 시스템을 모두 알아보세요"^]이전 환경에서 사용 가능했던 기능입니다. 여기에는 S3 서버로 사용한 ONTAP 시스템이 포함됩니다.
. https://docs.netapp.com/us-en/storage-management-storagegrid/task-discover-storagegrid.html["StorageGRID 시스템을 알아보세요"^] .




=== StorageGRID 환경 세부 정보 설정

원래 콘솔 에이전트 설정에서 설정된 대로 ONTAP 시스템과 연결된 StorageGRID 시스템의 세부 정보를 추가합니다. https://docs.netapp.com/us-en/console-automation/index.html["NetApp 콘솔 API"^] .

다음 정보는 NetApp Console 3.9.xx부터 시작하는 개인 모드 설치에 적용됩니다. 이전 버전의 경우 다음 절차를 따르세요. https://community.netapp.com/t5/Tech-ONTAP-Blogs/DarkSite-Cloud-Backup-MySQL-and-Indexed-Catalog-Backup-and-Restore/ba-p/440800["DarkSite 클라우드 백업: MySQL 및 인덱스 카탈로그 백업 및 복원"^] .

StorageGRID 에 데이터를 백업하는 각 시스템에 대해 이러한 단계를 수행해야 합니다.

. 다음 oauth/token API를 사용하여 권한 부여 토큰을 추출합니다.
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":"admin@netapp.com","password":"Netapp@123","grant_type":"password"}
> '
----
+
IP 주소, 사용자 이름, 비밀번호는 사용자 지정 값이지만 계정 이름은 그렇지 않습니다. 계정 이름은 항상 "account-DARKSITE1"입니다. 또한, 사용자 이름은 이메일 형식의 이름을 사용해야 합니다.

+
이 API는 다음과 같은 응답을 반환합니다. 아래와 같이 인증 토큰을 검색할 수 있습니다.

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. 테넌시/외부/리소스 API를 사용하여 시스템 ID와 X-Agent-Id를 추출합니다.
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
이 API는 다음과 같은 응답을 반환합니다. "resourceIdentifier" 아래의 값은 _WorkingEnvironment Id_를 나타내고 "agentId" 아래의 값은 _x-agent-id_를 나타냅니다.

. 시스템과 연결된 StorageGRID 시스템의 세부 정보로 NetApp 백업 및 복구 데이터베이스를 업데이트합니다. 아래와 같이 StorageGRID 의 정규화된 도메인 이름, 액세스 키, 스토리지 키를 입력해야 합니다.
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== NetApp 백업 및 복구 설정 확인

. 각 ONTAP 시스템을 선택하고 오른쪽 패널의 백업 및 복구 서비스 옆에 있는 *백업 보기*를 클릭합니다.
+
볼륨에 대해 생성된 모든 백업을 볼 수 있어야 합니다.

. 복원 대시보드의 검색 및 복원 섹션에서 *인덱싱 설정*을 클릭합니다.
+
이전에 색인 카탈로그 기능이 활성화된 시스템은 계속 활성화된 상태로 유지되는지 확인하세요.

. 검색 및 복원 페이지에서 몇 가지 카탈로그 검색을 실행하여 인덱싱된 카탈로그 복원이 성공적으로 완료되었는지 확인합니다.

