---
sidebar: sidebar 
permalink: reference-policy-differences-snapcenter.html 
keywords: backup policy, backup policies, snapcenter, migration 
summary: NetApp Backup and Recovery 에서 사용되는 정책과 SnapCenter 에서 사용되는 정책 사이에는 몇 가지 차이점이 있습니다. 
---
= SnapCenter 의 정책과 NetApp Backup and Recovery 정책 비교
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapCenter 에서 사용되는 정책과 NetApp Backup and Recovery 에서 사용되는 정책 사이에는 몇 가지 차이점이 있으며, 이는 SnapCenter 에서 리소스와 정책을 가져온 후에 표시되는 내용에 영향을 줄 수 있습니다.



== 일정 계층

SnapCenter 다음과 같은 일정 계층을 사용합니다.

* *시간별*: 여러 시간과 분, 모든 시간(0-23)과 모든 분(0-60).
* *매일*: 예를 들어 3일마다와 같이 설정된 일수마다 반복하는 옵션입니다.
* *주간*: 일요일부터 월요일까지, 주 1일 또는 주 여러 요일에 걸쳐 스냅샷을 수행할 수 있는 옵션이 제공됩니다.
* *월별*: 1월부터 12월까지, 예를 들어 매월 7일 등 특정 날짜나 여러 날에 공연할 수 있는 옵션이 있습니다.


NetApp Backup and Recovery 다음과 같은 약간 다른 일정 계층을 사용합니다.

* *매시간*: 15분 간격으로만 스냅샷을 수행합니다. 예를 들어, 60보다 짧은 1시간 또는 15분 간격으로 스냅샷을 수행합니다.
* *매일*: 하루 중 시간(0-23)이며, 예를 들어 오전 10시에 시작하며, 몇 시간마다 수행할지 선택할 수 있습니다.
* *주간*: 요일(일요일부터 월요일까지)에 따라 1일 또는 여러 날 공연할 수 있는 옵션이 제공됩니다.  이는 SnapCenter 와 동일합니다.
* *매월*: 매월 여러 날짜로 시작 시간을 지정한 날짜(0~30)입니다.
* *연간*: 월간.  이는 SnapCenter의 월별 요금과 일치합니다.




== 동일한 일정 계층을 가진 SnapCenter 의 여러 정책

SnapCenter 에서 리소스에 동일한 일정 계층을 사용하여 여러 정책을 할당할 수 있습니다.  하지만 NetApp Backup and Recovery 동일한 일정 계층을 사용하는 리소스에 대해 여러 정책을 지원하지 않습니다.

*예*: SnapCenter 에서 세 가지 정책(데이터, 로그 및 스냅샷 로그)을 사용하는 경우 SnapCenter 에서 마이그레이션한 후 NetApp Backup and Recovery 세 가지 정책 모두 대신 단일 정책을 사용합니다.



== SnapCenter 일일 일정 가져오기

NetApp Backup and Recovery SnapCenter 일정을 다음과 같이 조정합니다.

* SnapCenter 일정이 7일 이하로 설정된 경우 NetApp Backup and Recovery 일정을 주별로 설정합니다. 주중에는 일부 스냅샷이 건너뜁니다.
+
*예*: 월요일부터 시작하여 3일마다 반복되는 SnapCenter 일일 정책이 있는 경우 NetApp Backup and Recovery 일정을 월요일, 목요일, 일요일로 매주로 설정합니다.  정확히 3일마다 진행되는 것이 아니기 때문에 어떤 날은 건너뛰기도 합니다.

* SnapCenter 일정이 7일보다 크게 설정된 경우 NetApp Backup and Recovery 일정을 월별로 설정합니다.  이번 달에는 일부 스냅샷이 건너뛰어질 예정입니다.
+
*예*: 매월 2일부터 10일마다 반복되는 SnapCenter 일일 정책이 있는 경우, 마이그레이션 후 NetApp Backup and Recovery 일정을 매월 2일, 12일, 22일로 설정합니다.  NetApp Backup and Recovery 다음 달에 일부 날짜를 건너뜁니다.





== SnapCenter 시간별 일정을 가져왔습니다.

1시간 이상의 반복 간격을 가진 SnapCenter 시간별 정책은 NetApp Backup and Recovery 에서 일일 정책으로 변환됩니다.

24의 계수가 아닌 반복 간격(예: 5, 7 등)을 사용하는 시간별 정책은 하루 중 일부 스냅샷을 건너뜁니다.

*예*: 오전 1시부터 5시간 간격으로 반복되는 SnapCenter 시간별 정책이 있는 경우, NetApp Backup and Recovery (마이그레이션 후)는 일정을 오전 1시, 오전 6시, 오전 11시, 오후 4시, 오후 9시로 5시간 간격으로 매일로 설정합니다.  일부 시간은 건너뛰어집니다. 오후 9시 이후에는 5시간마다 반복하기 위해 오전 2시가 되어야 하지만 항상 오전 1시가 됩니다.



== SnapCenter 정책의 로그 보존

SnapCenter 에 여러 정책이 적용된 리소스가 있는 경우 NetApp Backup and Recovery 다음 우선 순위를 사용하여 로그 보존 값을 할당합니다.

* SnapCenter 의 "로그 백업 정책을 사용한 전체 백업"과 "로그 전용" 정책의 경우, NetApp Backup and Recovery 로그 전용 정책 보존 값을 사용합니다.
* SnapCenter 의 "로그만 포함한 전체 백업" 및 "전체 및 로그" 정책의 경우 NetApp Backup and Recovery 로그 전용 보존 값을 사용합니다.
* SnapCenter 의 "전체 백업 및 로그"와 "전체 백업"의 경우, NetApp Backup and Recovery "전체 백업 및 로그" 보존 값을 사용합니다.
* SnapCenter 에 전체 백업만 있는 경우 NetApp Backup and Recovery 로그 백업을 활성화하지 않습니다.




== 로그 백업 보존

SnapCenter 리소스의 정책에 대해 여러 보존 값을 지원합니다.  NetApp Backup and Recovery 리소스당 하나의 보존 값만 지원합니다.



== SnapCenter 정책의 보존 횟수

SnapCenter 에서 여러 소스 볼륨, 여러 대상 볼륨 및 여러 SnapMirror 관계가 있는 보조 보호가 활성화된 리소스가 있는 경우 NetApp Backup and Recovery 첫 번째 정책의 보존 횟수만 사용합니다.

*예*: 보존 횟수가 5인 SnapCenter 정책과 보존 횟수가 10인 다른 정책이 있는 경우 NetApp Backup and Recovery 보존 횟수 5를 사용합니다.



== SnapCenter 정책의 SnapMirror 레이블

SnapCenter 계층이 변경되더라도 마이그레이션 후에도 각 정책에 대한 SnapMirror 레이블을 유지합니다.

*예*: SnapCenter 의 시간당 정책이 NetApp Backup and Recovery 에서 일당 정책으로 변경될 수 있습니다.  하지만 SnapMirror 레이블은 마이그레이션 후에도 동일하게 유지됩니다.
