---
sidebar: sidebar 
permalink: task-preview-enable.html 
keywords: cloud backup, NetApp Backup and Recovery, backup, restore, preview, enable, object storage, third-party, MinIO, S3-compatible 
summary: 사용자가 시작하거나 예약한 로컬 스냅샷, 복제 및 개체 스토리지 백업 작업의 상태를 모니터링하고 사용자가 시작하거나 예약한 작업을 복원할 수 있습니다.  완료된 작업, 진행 중인 작업 또는 실패한 작업을 확인하여 문제를 진단하고 해결할 수 있습니다.  알림 센터를 사용하면 이메일로 알림을 보낼 수 있으므로 시스템에 로그인하지 않아도 중요한 시스템 활동에 대한 정보를 받을 수 있습니다.  타임라인을 사용하면 UI나 API를 통해 시작된 모든 작업의 세부 정보를 볼 수 있습니다. 
---
= NetApp 백업 및 복구에서 미리 보기 기능 활성화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 백업 및 복구는 새로운 기능이 완전히 출시되기 전에 테스트할 수 있는 미리보기 기능을 제공합니다.  이러한 기능은 백업 및 복구 환경을 개선하도록 설계되었지만, 완벽하게 지원되지 않거나 안정적이지 않을 수 있습니다.


IMPORTANT: 이러한 기능은 미리보기 모드에 있으므로 실제 운영 환경에서는 사용하면 안 됩니다.  이는 테스트 및 피드백 목적으로만 사용됩니다.



== 미리보기 기능 활성화

NetApp Backup and Recovery에서 미리 보기 기능을 활성화하려면 콘솔 에이전트에 플래그를 설정해야 합니다.  이 플래그를 사용하면 서비스에서 사용 가능한 미리보기 기능에 액세스하여 테스트할 수 있습니다.

.단계
. 콘솔 에이전트에 로그인합니다.
. 슈퍼유저로 전환합니다.  다음 명령을 실행합니다:
+
`sudo su`

. Docker 볼륨을 나열하고 CBS 볼륨을 식별합니다.  다음 명령을 실행합니다:
+
[listing]
----
podman volume ls | grep cbs
----
+
예상 출력:

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
. 볼륨을 검사하여 마운트 지점을 가져옵니다.  다음 명령을 실행합니다:
+
[listing]
----
podman volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
. 다음 명령을 실행합니다:
+
[listing]
----
podman volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
예상 출력:

+
[listing]
----
Mountpoint:
/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Docker Volumes 디렉토리로 이동합니다.  이전 단계에서 얻은 마운트 지점으로 디렉토리를 변경합니다.
+
[listing]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data/cbs_config

----
. 찾아서 편집하세요 `production-customer.json` 파일.
. 올바른 디렉토리에 있는지 확인하십시오. `production-customer.json` 파일이 존재합니다.
. 열기 `production-customer.json` 원하는 텍스트 편집기에서 파일을 열고 다음 JSON 스니펫을 추가하여 JSON 구조가 제대로 유지되도록 합니다.
+
[listing]
----
{
   "feature-flags":
    {
        "volumes-dashboard-v2": true
     }
}
----
. 파일의 변경 사항을 저장합니다.
. NetApp Backup and Recovery Cloud Manager CBS 서비스를 다시 시작합니다.  다음 명령을 실행합니다:
+
[listing]
----
podman restart cloudmanager_cbs
----

