= 1GB 미만의 볼륨 복원
:allow-uri-read: 




=== 1GB 미만의 볼륨 복원

이 릴리스를 사용하면 ONTAP 에서 생성한 1GB 미만의 볼륨을 복원할 수 있습니다.  ONTAP 사용하여 생성할 수 있는 최소 볼륨 크기는 20MB입니다.



=== DataLock 비용을 완화하는 방법에 대한 팁

DataLock 기능은 지정된 기간 동안 백업 파일이 수정되거나 삭제되는 것을 방지합니다.  이는 랜섬웨어 공격으로부터 파일을 보호하는 데 도움이 됩니다.

DataLock에 대한 자세한 내용과 관련 비용을 완화하는 방법에 대한 팁은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-policy-object-options.html["개체 백업 정책 설정"] .



=== AWS IAM Roles Anywhere 통합

Amazon Web Services(AWS) Identity and access Roles Anywhere 서비스를 사용하면 AWS _외부_의 워크로드에 대한 IAM 역할과 단기 자격 증명을 사용하여 AWS API에 안전하게 액세스할 수 있습니다. 이는 AWS _내_ 워크로드에 대한 IAM 역할을 사용하는 것과 같은 방식입니다.  IAM Roles Anywhere 개인 키 인프라와 AWS 토큰을 사용하면 장기 AWS 액세스 키와 비밀 키가 필요하지 않습니다.  이를 통해 자격 증명을 더 자주 교체할 수 있어 보안이 향상됩니다.

이 릴리스에서는 AWS IAM Roles Anywhere 서비스에 대한 지원이 기술 미리 보기로 제공됩니다.

ifdef::aws[]

이것은 다음에 적용됩니다link:prev-ontap-backup-cvo-aws.html["AWS에 Cloud Volumes ONTAP 백업"] .

endif::aws[]

참조하다 https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["NetApp 백업 및 복구 2024년 7월 릴리스 블로그"] .



=== FlexGroup 폴더 또는 디렉토리 복원이 이제 가능합니다.

이전에는 FlexVol 볼륨은 복원할 수 있었지만 FlexGroup 폴더나 디렉토리는 복원할 수 없었습니다.  ONTAP 9.15.1 p2를 사용하면 찾아보기 및 복원 옵션을 사용하여 FlexGroup 폴더를 복원할 수 있습니다.

이 릴리스에서는 FlexGroup 폴더 복원에 대한 지원이 기술 미리보기로 제공됩니다.

자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["찾아보기 및 복원을 사용하여 폴더 및 파일 복원"] .

수동으로 활성화하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["NetApp 백업 및 복구 2024년 7월 릴리스 블로그"] .
