= UI 개선
:allow-uri-read: 




=== UI 개선

이번 릴리스에서는 인터페이스를 단순화하여 사용자 경험을 향상시킵니다.

* V2 대시보드의 볼륨 테이블에서 집계 열과 스냅샷 정책, 백업 정책, 복제 정책 열이 제거되어 레이아웃이 더욱 간소화되었습니다.
* 활성화되지 않은 작업 환경을 드롭다운 목록에서 제외하면 인터페이스가 간결해지고, 탐색 효율성이 높아지며, 로딩 속도도 빨라집니다.
* 태그 열의 정렬 기능이 비활성화되어 있어도 태그를 계속 볼 수 있으므로 중요한 정보에 쉽게 접근할 수 있습니다.
* 보호 아이콘의 라벨을 제거하면 모양이 더 깔끔해지고 로딩 시간도 단축됩니다.
* 작업 환경 활성화 프로세스 동안 대화 상자에 로딩 아이콘이 표시되어 검색 프로세스가 완료될 때까지 피드백을 제공하여 시스템 운영의 투명성과 신뢰도를 높입니다.




=== 향상된 볼륨 대시보드(미리 보기)

이제 볼륨 대시보드가 10초 이내에 로드되어 훨씬 더 빠르고 효율적인 인터페이스를 제공합니다.  이 미리보기 버전은 일부 고객에게만 제공되며, 이를 통해 이러한 개선 사항을 미리 살펴볼 수 있습니다.



=== 타사 Wasabi 객체 저장소 지원(미리 보기)

NetApp Backup and Recovery는 이제 Wasabi를 중심으로 타사 개체 저장소에 대한 지원을 확장했습니다.  이 새로운 미리보기 기능을 사용하면 백업 및 복구 요구 사항에 맞게 모든 S3 호환 개체 저장소를 활용할 수 있습니다.



==== 와사비 시작하기

타사 저장소를 개체 저장소로 사용하려면 콘솔 에이전트 내에서 플래그를 활성화해야 합니다.  그런 다음 타사 개체 저장소에 대한 연결 세부 정보를 입력하고 이를 백업 및 복구 워크플로에 통합할 수 있습니다.

.단계
. 커넥터에 SSH를 실행합니다.
. NetApp Backup and Recovery CBS 서버 컨테이너로 이동합니다.
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. 열기 `default.json` 파일 내부 `config` VIM이나 다른 편집기를 통해 폴더로 이동:
+
[listing]
----
vi default.json
----
. 수정하다 `allow-s3-compatible` : 거짓 `allow-s3-compatible` : 진실.
. 변경 사항을 저장합니다.
. 컨테이너에서 나오세요.
. NetApp 백업 및 복구 CBS 서버 컨테이너를 다시 시작합니다.


.결과
컨테이너가 다시 켜지면 NetApp 백업 및 복구 UI를 엽니다.  백업을 시작하거나 백업 전략을 편집하면 AWS, Microsoft Azure, Google Cloud, StorageGRID, ONTAP S3의 ​​다른 백업 공급자와 함께 새로운 공급자 "S3 호환"이 나열됩니다.



==== 미리보기 모드 제한 사항

이 기능은 아직 미리보기 단계에 있지만 다음과 같은 제한 사항을 고려하세요.

* BYOB(Bring Your Own Bucket)는 지원되지 않습니다.
* 정책에서 DataLock을 활성화하는 것은 지원되지 않습니다.
* 정책에서 보관 모드를 활성화하는 것은 지원되지 않습니다.
* 온프레미스 ONTAP 환경만 지원됩니다.
* MetroCluster 지원되지 않습니다.
* 버킷 수준 암호화를 활성화하는 옵션은 지원되지 않습니다.


이 미리 보기 기간 동안 새로운 기능을 살펴보고 전체 기능이 출시되기 전에 타사 개체 저장소와의 통합에 대한 피드백을 제공해 주시기 바랍니다.
