= 고성능 인덱싱
:allow-uri-read: 




=== 고성능 인덱싱

NetApp Backup and Recovery 소스 시스템의 데이터 인덱싱을 보다 효율적으로 만들어 주는 업데이트된 인덱싱 기능을 도입했습니다.  새로운 인덱싱 기능에는 UI 업데이트, 데이터 복원을 위한 검색 및 복원 방법의 성능 개선, 글로벌 검색 기능 업그레이드, 확장성 향상 등이 포함됩니다.

개선 사항에 대한 세부 내용은 다음과 같습니다.

* *폴더 통합*: 업데이트된 버전에서는 특정 식별자를 포함하는 이름을 사용하여 폴더를 그룹화하여 인덱싱 프로세스를 더욱 원활하게 만들었습니다.
* *Parquet 파일 압축*: 업데이트된 버전에서는 각 볼륨을 인덱싱하는 데 사용되는 파일 수가 줄어들어 프로세스가 간소화되고 추가 데이터베이스가 필요하지 않습니다.
* *더 많은 세션으로 확장*: 새로운 버전에서는 인덱싱 작업을 처리하기 위해 더 많은 세션을 추가하여 프로세스 속도를 높였습니다.
* *여러 인덱스 컨테이너 지원*: 새 버전에서는 여러 컨테이너를 사용하여 인덱싱 작업을 보다 효과적으로 관리하고 분산합니다.
* *분할 색인 워크플로*: 새로운 버전에서는 색인 프로세스를 두 부분으로 나누어 효율성을 높였습니다.
* *동시성 향상*: 새로운 버전에서는 디렉토리를 동시에 삭제하거나 이동할 수 있어 인덱싱 프로세스가 빨라집니다.


.이 기능의 이점은 누구에게 있나요?
새로운 인덱싱 기능은 모든 신규 고객에게 제공됩니다.

.인덱싱을 어떻게 활성화하나요?
검색 및 복원 방법을 사용하여 데이터를 복원하려면 먼저 볼륨이나 파일을 복원할 각 소스 시스템에서 "인덱싱"을 활성화해야 합니다.  이를 통해 색인 카탈로그는 모든 볼륨과 모든 백업 파일을 추적하여 검색을 빠르고 효율적으로 수행할 수 있습니다.

검색 및 복원을 수행할 때 "인덱싱 사용" 옵션을 선택하여 소스 작업 환경에서 인덱싱을 활성화합니다.

자세한 내용은 설명서를 참조하세요. https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["Search  Restore를 사용하여 ONTAP 데이터를 복원하는 방법"] .

.지원되는 규모
새로운 인덱싱 기능은 다음을 지원합니다.

* 3분 이내에 글로벌 검색 효율성 향상
* 최대 50억 개의 파일
* 클러스터당 최대 5000개의 볼륨
* 볼륨당 최대 100K 스냅샷
* 기준 색인에 걸리는 최대 시간은 7일 미만입니다.  실제 시간은 환경에 따라 달라집니다.




=== 글로벌 검색 성능 개선

이번 릴리스에는 글로벌 검색 성능이 향상되었습니다.  이제 진행률 표시기와 더 자세한 검색 결과를 볼 수 있습니다. 여기에는 파일 수와 검색에 걸린 시간이 포함됩니다.  검색 및 인덱싱을 위한 전용 컨테이너를 통해 글로벌 검색을 5분 이내에 완료할 수 있습니다.

글로벌 검색과 관련된 다음 고려 사항을 참고하세요.

* 새로운 인덱스는 시간별로 표시된 스냅샷에서는 수행되지 않습니다.
* 새로운 인덱싱 기능은 FlexVols의 스냅샷에만 작동하고 FlexGroups의 스냅샷에는 작동하지 않습니다.

