= 볼륨 마이그레이션을 위한 SnapMirror to Cloud Resync
:allow-uri-read: 




=== 볼륨 마이그레이션을 위한 SnapMirror to Cloud Resync

SnapMirror to Cloud Resync 기능은 NetApp 환경에서 볼륨 마이그레이션 중에 데이터 보호와 연속성을 간소화합니다. SnapMirror Logical Replication(LRSE)을 사용하여 볼륨을 온프레미스 NetApp 배포에서 다른 배포로 또는 Cloud Volumes ONTAP 과 같은 클라우드 기반 솔루션으로 마이그레이션하는 경우 SnapMirror to Cloud Resync를 통해 기존 클라우드 백업이 손상되지 않고 작동 상태를 유지하도록 보장합니다.

이 기능을 사용하면 시간이 많이 걸리고 리소스가 많이 필요한 재기준화 작업이 필요 없으므로 마이그레이션 후에도 백업 작업을 계속할 수 있습니다.  이 기능은 FlexVol과 FlexGroup을 모두 지원하여 워크로드 마이그레이션 시나리오에서 유용하며 ONTAP 버전 9.16.1부터 사용할 수 있습니다.

SnapMirror to Cloud Resync는 여러 환경 간에 백업 연속성을 유지함으로써 운영 효율성을 높이고 하이브리드 및 멀티 클라우드 데이터 관리의 복잡성을 줄여줍니다.

재동기화 작업을 수행하는 방법에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-migrate-resync.html["SnapMirror 사용하여 볼륨을 Cloud Resync로 마이그레이션"] .



=== 타사 MinIO 객체 저장소 지원(미리 보기)

NetApp Backup and Recovery 이제 MinIO에 중점을 두고 타사 개체 저장소에 대한 지원을 확장했습니다.  이 새로운 미리보기 기능을 사용하면 백업 및 복구 요구 사항에 맞게 모든 S3 호환 개체 저장소를 활용할 수 있습니다.

이 미리보기 버전을 통해 전체 기능이 출시되기 전에 타사 개체 저장소와의 강력한 통합을 보장하고자 합니다.  여러분은 이 새로운 기능을 살펴보고 서비스 개선에 도움이 되는 피드백을 제공해 주시기 바랍니다.


IMPORTANT: 이 기능은 실제 운영 환경에서는 사용하면 안 됩니다.

*미리보기 모드 제한 사항*

이 기능은 아직 미리보기 단계에 있지만 다음과 같은 몇 가지 제한 사항이 있습니다.

* BYOB(Bring Your Own Bucket)는 지원되지 않습니다.
* 정책에서 DataLock을 활성화하는 것은 지원되지 않습니다.
* 정책에서 보관 모드를 활성화하는 것은 지원되지 않습니다.
* 온프레미스 ONTAP 환경만 지원됩니다.
* MetroCluster 지원되지 않습니다.
* 버킷 수준 암호화를 활성화하는 옵션은 지원되지 않습니다.


*시작하기*

이 미리 보기 기능을 사용하려면 콘솔 에이전트에서 플래그를 활성화해야 합니다.  그런 다음 백업 섹션에서 *타사 호환* 개체 저장소를 선택하여 보호 워크플로에서 MinIO 타사 개체 저장소의 연결 세부 정보를 입력할 수 있습니다.
