= 일반 NetApp Backup and Recovery 기능 향상
:allow-uri-read: 




[[general-netapp-backup-and-recovery-enhancement]]
=== 일반 NetApp Backup and Recovery 기능 향상

이번 릴리스에서는 KVM, Hyper-V 및 VMware 워크로드에 다음과 같은 개선 사항이 도입되었습니다.

*VM 호스트 검색 중 자격 증명 선택*: KVM, Hyper-V 또는 VMware 호스트를 검색할 때 Backup and Recovery에 이미 추가한 자격 증명을 사용할 수 있습니다.



[[hyper-v-workloads-enhancement]]
=== Hyper-V 워크로드 향상

이번 릴리스에서 Hyper-V 워크로드는 다음과 같은 개선 사항을 도입했습니다.

*VM에 대한 디스크 보호 기능 확장*: CIFS 구성의 경우, 백업 및 복구 기능은 이제 보호 그룹에 속한 각 VM에 연결된 모든 디스크를 보호할 수 있도록 지원합니다. 여기에는 여러 ONTAP 볼륨 또는 ONTAP 스토리지 시스템(스패닝 디스크)에 분산된 파일과 단일 위치에만 있는 파일이 모두 포함됩니다.

Hyper-V 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["NetApp Backup and Recovery를 사용하여 Hyper-V 워크로드를 보호하는 방법에 대해 알아보십시오."]를 참조하십시오.



[[ontap-volumes-workloads-enhancement]]
=== ONTAP Volumes 워크로드 향상

이번 릴리스에서 ONTAP Volumes 워크로드는 다음과 같은 미리 보기 개선 사항을 도입합니다.

*일일 백업 데이터 전송 보고서*: NetApp Backup and Recovery for Volumes에 이제 보고서 탭에서 이용 가능한 일일 백업 데이터 전송 보고서가 포함되어 있어 환경 전반의 일일 백업 및 복제 데이터 전송 활동을 확인할 수 있습니다. 전체 계정 또는 선택한 스토리지 시스템에 대한 보고서를 생성하고, 날짜 범위 및 보호 유형별로 필터링한 후 CSV 파일로 다운로드할 수 있습니다.

ONTAP Volumes 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recovery를 사용한 ONTAP 볼륨 보호에 대해 알아보십시오"]를 참조하십시오.
