= ONTAP Volumes 워크로드 향상
:allow-uri-read: 




[[ontap-volumes-workloads-enhancement]]
=== ONTAP Volumes 워크로드 향상

이번 릴리스에서 ONTAP Volumes 워크로드는 다음과 같은 미리 보기 개선 사항을 도입합니다.

*다크 사이트 지원 강화*: NetApp Backup and Recovery for dark sites는 이제 NetApp Backup and Recovery와 동일한 ONTAP Volumes 데이터 보호 기능을 제공합니다. 이 개선 사항에는 업데이트된 백업, 복원 및 작업 관리 서비스와 새로운 메타데이터 데이터베이스가 포함됩니다. 업그레이드 시 기존 데이터베이스 데이터는 자동으로 보존되고 마이그레이션됩니다. 업그레이드 후 감사 로그를 검토하여 마이그레이션이 성공적으로 완료되었는지 확인하십시오. NetApp Backup and Recovery for dark sites는 ONTAP Volumes 워크로드만 지원합니다.

ONTAP Volumes 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recovery를 사용한 ONTAP 볼륨 보호에 대해 알아보십시오"]를 참조하십시오.



[[kubernetes-workloads-enhancements]]
=== Kubernetes 워크로드 개선 사항

이번 릴리스에서 Kubernetes 워크로드는 다음과 같은 개선 사항을 도입했습니다.

* *Trident Protect 26.09*: 이번 릴리스에는 Trident Protect 26.09가 포함되어 있습니다.
* *클러스터 및 네임스페이스 수준의 역할 기반 액세스 제어(RBAC)*: Kubernetes 클러스터 검색 중에 새 클러스터와 연결할 프로젝트 또는 폴더를 선택하여 리소스에 대한 액세스를 제어할 수 있습니다. 특정 네임스페이스를 등록하여 액세스 제어를 수행할 수도 있습니다. 이를 통해 클러스터 또는 네임스페이스 수준에서 더욱 세밀한 액세스 제어가 가능합니다.
* *파일 및 폴더 복원*: 이제 Kubernetes VM 기반 애플리케이션 백업에서 특정 파일 및 폴더를 복원하거나 다운로드할 수 있습니다.


Kubernetes 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["NetApp Backup and Recovery를 사용하여 Kubernetes 워크로드를 보호하는 방법에 대해 알아보십시오."]을 참조하세요.
