= ONTAP 볼륨 워크로드 개선 사항
:allow-uri-read: 




=== ONTAP 볼륨 워크로드 개선 사항

ONTAP 볼륨 워크로드의 이번 릴리스에서는 다음과 같은 향상된 기능이 도입되었습니다.

*다중 버킷 지원*: (비공개 미리 보기) ONTAP 9.17.1 이상 버전부터 시스템 내 볼륨을 서로 다른 클라우드 공급자에 걸쳐 시스템당 최대 6개의 버킷으로 보호할 수 있습니다.

link:prev-ontap-backup-manage.html["NetApp Backup and Recovery 사용하여 ONTAP 볼륨 데이터를 백업하는 방법에 대해 자세히 알아보세요."].



=== VMware 워크로드 개선 사항

이번 VMware 워크로드 릴리스에서는 다음과 같은 향상된 기능이 도입되었습니다.

* NetApp Backup and Recovery에서 VMware 워크로드 지원이 이제 정식 출시(GA)되었습니다.
* 이제 게스트 OS 파일과 폴더를 복원할 수 있습니다.


https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-overview.html["게스트 파일 및 폴더 복원에 대해 자세히 알아보세요."].



=== Hyper-V 워크로드 미리 보기 개선 사항

이번 Hyper-V 워크로드 릴리스에서는 다음과 같은 향상된 기능이 도입되었습니다.

* 이제 Hyper-V VM 백업 및 스냅샷을 다른 위치로 복원할 수 있습니다. 이 기능을 사용하여 서로 다른 Hyper-V 호스트에서 VM 버전을 관리할 수 있습니다.
* NetApp Backup and Recovery는 이제 System Center Virtual Machine Manager(SCVMM)로 프로비저닝되고 CIFS 공유에서 호스팅되는 Hyper-V 가상 머신을 지원합니다.
* 이제 보호 그룹을 편집할 수 있습니다.



NOTE: 이번 릴리스에서는 작업 메뉴의 *업그레이드* 옵션을 사용하여 Hyper-V 또는 Windows용 NetApp 플러그인을 업그레이드할 수 없습니다. 그 대신 각 Hyper-V 호스트를 제거한 다음 다시 추가하여 플러그인을 업데이트하십시오.

https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-restore.html["NetApp Backup and Recovery 사용하여 Hyper-V VM을 복원하는 방법에 대해 자세히 알아보세요."].



=== KVM 워크로드 미리 보기 개선 사항

KVM 워크로드 미리 보기 기능은 이제 Apache CloudStack에서 관리하는 KVM 호스트 및 가상 머신을 보호합니다.

KVM 작업 부하 보호에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["KVM 워크로드 보호 개요"] .
