= Kubernetes 워크로드 개선 사항
:allow-uri-read: 




=== Kubernetes 워크로드 개선 사항

이번 Kubernetes 워크로드 릴리스에서는 다음과 같은 향상된 기능이 도입되었습니다.

* *CR 워크플로우 지원*: 이제 NetApp Backup and Recovery 웹 UI뿐만 아니라 CR을 사용하여 일반적인 보호 작업을 수행할 수 있습니다.
* *클러스터 마이그레이션*: 이제 Trident Protect로 보호되는 기존 Kubernetes 클러스터를 Backup and Recovery에 추가할 수 있습니다.
* *알림 프레임워크 지원*: 이제 특정 Kubernetes 워크로드 이벤트에 대한 이메일 및 UI 알림을 받을 수 있습니다.
* *복원 탭 통합*: 이제 복원 메뉴에서 Kubernetes 워크로드 복원 작업에 액세스할 수 있습니다.
* *3-2-1 팬아웃 백업 아키텍처 지원*: 이제 Kubernetes 워크로드를 보호할 때 보호 정책에서 3-2-1 팬아웃 아키텍처를 사용할 수 있습니다.


Kubernetes 워크로드 보호에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Kubernetes 워크로드 보호 개요"] .



=== Oracle Database 워크로드 개선 사항

이번 Oracle Database 워크로드 릴리스에서는 다음과 같은 향상된 기능이 도입되었습니다.

* *루트 권한이 없는 사용자 지원*: 이제 루트 권한이 없는 사용자도 백업, 복원 및 복제 작업을 수행할 수 있어 보안 및 규정 준수가 향상됩니다.
* *클론 지원*: 이제 ASM 라이브러리 v2를 사용하여 운영 및 2차 NAS, SAN 및 ASM 환경 전반에 걸쳐 클론 기능을 지원하여 통합 보호 워크플로를 구현할 수 있습니다.
* *클론 분할 지원*: 이제 쓰기 가능한 스냅샷(클론)을 상위 볼륨에서 분할하여 스토리지를 확보하고 독립적인 작업을 수행할 수 있습니다.
* *객체 저장소에 대한 백업 및 복원*: 이제 객체 기반 S3 호환 스토리지 타겟에 대한 네이티브 백업 및 복원 기능이 지원됩니다.
* *Clone Lifecycle Management(CLM)*: 운영 스토리지에서 클론 새로 고침 작업이 지원됩니다.
* *다른 호스트로 복제*: 이제 기본 스토리지와 2차 스토리지 모두에서 데이터베이스를 다른 호스트로 복제할 수 있습니다(테스트 또는 분석용).
* *ONTAP 일관성 그룹 지원*: 이제 ONTAP 일관성 그룹이 지원되어 여러 볼륨에서 애플리케이션 정합성 보장 스냅샷을 보장합니다.
* 이제 NetApp Backup and Recovery는 Oracle Database 워크로드에 대해 다음과 같은 보호 정책 아키텍처를 지원합니다.
+
** 3-2-1 팬아웃
** 디스크 간
** 디스크에서 오브젝트 스토리지로
** 캐스케이딩
** 로컬 스냅샷




Oracle Database 워크로드 보호에 대한 자세한 내용은 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Oracle Database 워크로드 보호 개요"]을 참조하십시오.



=== 기타 개선 사항

Hyper-V 워크로드, KVM 워크로드 및 VMware 워크로드가 이제 NetApp Backup and Recovery에서 정식 출시(GA)되었습니다.
