= 복원 및 페일오버 작업 중 네임스페이스 주석 및 레이블
:allow-uri-read: 




== 복원 및 페일오버 작업 중 네임스페이스 주석 및 레이블

복원 및 페일오버 중에 대상 네임스페이스 레이블과 주석은 소스와 일치하도록 업데이트됩니다. 소스의 키가 대상 키에 추가되거나 덮어쓰여지고, 대상에만 존재하는 키는 변경되지 않고 그대로 유지됩니다.


NOTE: Red Hat OpenShift에서 네임스페이스 어노테이션은 복원된 Pod가 올바른 보안 컨텍스트 제약 조건과 권한을 받도록 보장하여 볼륨에 액세스하고 권한 오류 없이 실행할 수 있도록 하므로 중요합니다. 자세한 내용은 link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["OpenShift 보안 컨텍스트 제약 조건 문서"^]을(를) 참조하십시오.

Kubernetes 환경 변수를 설정합니다

[listing]
----
RESTORE_SKIP_NAMESPACE_ANNOTATIONS
----
복원 또는 장애 조치 전에 특정 대상 네임스페이스 주석이 덮어쓰여지는 것을 방지합니다. 예를 들면 다음과 같습니다.

[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set-string restoreSkipNamespaceAnnotations="{<annotation_key_to_skip_1>,<annotation_key_to_skip_2>}" \
  --reuse-values
----

NOTE: 복원 또는 페일오버 중에 `restoreSkipNamespaceAnnotations` 및 `restoreSkipNamespaceLabels`에 지정된 네임스페이스 어노테이션 및 레이블은 복원 또는 페일오버 작업에서 제외됩니다. 초기 Helm 설치 시 이러한 설정이 구성되어 있는지 확인하십시오. 자세한 내용은 https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Trident Protect 헬름 차트의 추가 설정을 구성합니다"]을 참조하십시오.

Helm을 사용하여  `--create-namespace` 플래그로 소스 애플리케이션을 설치한 경우, Trident Protect는 이름 레이블을 대상 네임스페이스로 복사합니다. 레이블 값이 소스 네임스페이스 이름과 일치하면 대상 네임스페이스 이름으로 대체되고, 일치하지 않으면 그대로 유지됩니다.



=== 예

다음 예는 서로 다른 레이블과 주석이 있는 소스 및 대상 네임스페이스를 보여주고, 키가 추가, 병합 또는 덮어쓰기되는 방식을 설명하기 위해 작업 전후의 대상 네임스페이스를 표시합니다.



==== 복원 또는 페일오버 작업 전에

다음 표는 복원 또는 페일오버 작업 전 예시 소스 및 대상 네임스페이스의 상태를 보여줍니다.

[cols="1,2a,2a"]
|===
| 네임스페이스 | 주석 | 라벨 


| 네임스페이스 ns-1(소스)  a| 
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"

 a| 
* environment=production
* 컴플라이언스=hipaa
* name=ns-1




| 네임스페이스 ns-2(대상)  a| 
* annotation.one/key: "true"
* annotation.three/key: "false"

 a| 
* role=database


|===


==== 복원 작업 후

다음 표는 복원 또는 장애 조치 작업 후 예시 대상 네임스페이스의 상태를 보여줍니다. 일부 키가 추가되었고, 일부는 덮어쓰여졌으며,  `name` 레이블은 대상 네임스페이스와 일치하도록 업데이트되었습니다.

[cols="1,2a,2a"]
|===
| 네임스페이스 | 주석 | 라벨 


| 네임스페이스 ns-2(대상)  a| 
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"
* annotation.three/key: "false"

 a| 
* name=ns-2
* 컴플라이언스=hipaa
* environment=production
* role=database


|===